### ISSUE TITLE
Generator Upgrade BREAKS the generators

### ISSUE THREAD

**Issue by Rophiang** [BedwarsRel/BedwarsRel#1012]
In my config.yml file, I changed the resources to iron, gold, diamonds, and emeralds to emulate a more hypixel-ish feel. I set the cooldown times to 1 second for iron, 10 seconds for gold, 20 for diamonds, and 1 min for emeralds. After the second generator upgrade,  the iron and gold generator completely breaks and only generate resources once every (it seems) 10 seconds!! 

If anyone knows how to fix this or what the issue is, please reply to this post ASAP 

Thanks!! 😄 

also, here is my config.yml just in case

https://pastebin.com/LigC38F1

**Comment by Rophiang** [comment]
Never mind. Just found out it was part of a plugin addon called bedwars scoreboard addon. :P

**Comment by SmartDeveloper20** [comment]
I had the same error and solved it in the BedwarsScoreboard config.yml
