### ISSUE TITLE
Bedwars GUI

### ISSUE THREAD

**Issue by NoobiousMcNoob** [BedwarsRel/BedwarsRel#1030]
Hi, it's me again
I was using the one with autojoin
how do I open the GUI? I cannot set bed positions.

**Comment by kubawis128** [comment]
GUI? I always used /bw setbed [game] [team]

**Comment by kubawis128** [comment]
GUI? I always used /bw setbed [game] [team] while standing on target bed.

**Comment by NoobiousMcNoob** [comment]
i think there was a GUI in the previous version..
