### ISSUE TITLE
Make the server slow

### ISSUE THREAD

**Issue by cc58c58** [BedwarsRel/BedwarsRel#461]
I add this plugin with 10 maps.But more player enter the server,the server more slow.How can i do? 
   http://i13.tietuku.cn/605e38e829f9c8b0.png

**Comment by sebastianbinder** [comment]
Are you using HolographicDisplays and ProtocolLib? I think there is a problem with the server sending to many updates to the client causing lags.

**Comment by cc58c58** [comment]
http://www.ephotobay.com/share/-w89ge07suo4u-8yos-d-w.html
http://www.ephotobay.com/share/j620baqkc1m46oj8j-v-g5q.html

Maybe not HolographicDisplays and ProtocolLib
