### ISSUE TITLE
[Bug] - Bedwars slow to respond

### ISSUE THREAD

**Issue by Orangeric88** [BedwarsRel/BedwarsRel#516]
**Problem**:
Sorry for interruption you guys again,
I have noticed yet another glitch, the one I said yesterday was indeed not from Bedwars,"[Thanks for clearing that up.] Ok so the bug is when you try to reload or end the server, it would just be stuck at this message, "[BedWarsRel] Disabling BedwarsRel v1.30".
The message would be there for about 2 min then the server would end up crashing, since their is no response. I have checked and it doesn't have to do with my server at all. (I run the server with 4GB of ram) Before, when I only had three bedwars game, this would go relatively fast, but now since I have 6 games, its been slow shutting/restarting the server. When you start the server, it goes fast, but when you restart/stop the server, like I said before, it is very slow.

**Version**:  My version for Bedwars reloaded is v1.3 Fixed Jar

**Spigot Version**:  My version of spigot is 1.9.2 or the latest update spigot handed out

**Server Setup**:  My server setup is in fact a single server

**Installed plugins**:  Bedwars Reloaded, World Edit, World Guard, Block Control, Title manager, SpawnJoin, Scoreboard Stats, ProtolcalLlib , PermissionsEX, Multiverse Core, Holographic Displays, Colored Signs, and Click Warp

**Shop**.yml: http://pastebin.com/6uQyxKc1

**config.yml**: http://pastebin.com/chqKHyj7

**Console Startup**: http://pastebin.com/w2X7Dn1a

**Errors on Console**: http://pastebin.com/Fwv1M1dC

**Comment by Orangeric88** [comment]
There we go, its an updated bug report of the last one.

**Comment by sebastianbinder** [comment]
@Orangeric88 Thank you. First of all, please fix all the issues from the other plugins or better remove every plugin (except BedwarsRel's dependencies) to make sure, the problem is really caused by BedwarsRel.

**Comment by Orangeric88** [comment]
@sebastianbinder Yes this is caused by Bedwars Reloaded. I removed every plugin besides Bedwar Reloaded, Holographic Displays, and ProtocolLib, and I still got the slow response.

**Comment by sebastianbinder** [comment]
@Orangeric88 still having problems with the plugin?

**Comment by Orangeric88** [comment]
Sadly yes, I'm still having that problem. It's still loads very slow to the point where it's going to crash. I just let it do what it does.. Eventually it will load up.

**Comment by sebastianbinder** [comment]
But I still don't really get the problem with BedwarsRel here. Any errors on the console lately?
