### ISSUE TITLE
platform

### ISSUE THREAD

**Issue by Fages** [BedwarsRel/BedwarsRel#576]
Hi, Could you add slime block support platform

**Comment by sebastianbinder** [comment]
What do you mean by that?

**Comment by Granik24** [comment]
@sebastianbinder I think, he thought about configurable blocks for resurrection platform? o.O But don't get, what players can get with slime blocks..

**Comment by sebastianbinder** [comment]
Afaik any block can be set for the platform…

**Comment by Granik24** [comment]
So, this issue don't have any sense.
