### ISSUE TITLE
LOCALE_NOT_FOUND

### ISSUE THREAD

**Issue by dreamenemy** [BedwarsRel/BedwarsRel#580]
### General Information
- **Version of BedwarsRel**: ``1.3.1``
- **Version of Spigot**: ``spigot-1.8.4-R0.1-SNAPSHOT-latest``
- **Server Setup**: ``Single Server``
- **Installed plugins**: ``authme,bedwarsrel,clearlag,essentialsx,essentialsxchat,essentialsxspawn,holographicdisplays,holographicscoreboard,multiversecore,permissionsex,protocollib,randomsk,sexymotd,skextras,skQuery,skript,superhub,vault,coidspawn,wildskript,worldedit,worldguard``
- **shop.yml**: [shop.yml](http://pastebin.com/2ss4ikDf)
- **config.yml**:  [config.yml](http://pastebin.com/NFnW6CwD)
- **Errors on the Console**: [logfile](http://pastebin.com/bJz6PVn5)

### Problem
my game sign 4. line say every time locale nor found sS:http://image.prntscr.com/image/8faa619aea194db18085887f1a03a746.png

**Comment by sebastianbinder** [comment]
Two things: Update to latest version 1.3.2 and if you have not modified your locales manually remove the "locale" directory within "plugins/BedwarsRel/.

**Comment by dreamenemy** [comment]
no its not work :(

**Comment by sebastianbinder** [comment]
@dreamenemy Update 1.3.3 with a lot of changes concerning locales is coming soon :)

**Comment by sebastianbinder** [comment]
@dreamenemy have you tried it?

**Comment by dreamenemy** [comment]
thank you i will wait announced version
