### ISSUE TITLE
Potions don't working

### ISSUE THREAD

**Issue by tacosgogame** [BedwarsRel/BedwarsRel#592]
All the directory of potions don't working! Why?
  drinks:
    item: POTION
    name: "Potions"
    order: 80
    permission: bw.base
    lore:
    - "Click, to buy potions!"
    offers:
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: healing
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: strong_healing
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: swiftness
    - price:
      - type: GOLD_INGOT
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: strength
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: regeneration

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by tacosgogame** [comment]
![2016-07-08_20 11 29](https://cloud.githubusercontent.com/assets/12693293/16695417/683717ce-4548-11e6-829f-b5d8c008a1f5.png)

`shop:
  armor:
    item: DIAMOND_CHESTPLATE
    name: Броня
    order: 10
    permission: bw.base
    lore:
    - Нажми, чтобы купить броню
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_BOOTS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
        amount: 6
      - type: GOLD_INGOT
      reward:
      - type: IRON_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Магнитные сапоги
          lore:
          - Одень эти сапоги и получи 75%
          - шанс поглотить отдачу!
    - price:
      - type: IRON_INGOT
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 3
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Шлем
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
  swords:
    item: DIAMOND_SWORD
    name: Мечи
    order: 20
    permission: bw.base
    lore:
    - Нажми, чтобы купить меч
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 8
      reward:
      - type: STICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1
    - price:
      - type: IRON_INGOT
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 3
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
            KNOCKBACK: 1
    - price:
      - type: GOLD_INGOT
        amount: 15
      reward:
      - type: GOLD_AXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Топор бесконечности
          enchants:
            DAMAGE_ALL: 1
            DURABILITY: 1
            KNOCKBACK: 1
  bows:
    item: 261
    name: Луки
    order: 30
    permission: bw.base
    lore:
    - Нажми, чтобы купить лук
    offers:
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 7
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 13
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 2
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 16
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 15
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_KNOCKBACK: 1
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ARROW
  eat:
    item: GRILLED_PORK
    name: Еда
    order: 40
    permission: bw.base
    lore:
    - Нажми, чтобы купить провизию
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GRILLED_PORK
        amount: 2
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: GOLDEN_APPLE
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: BREAD
        amount: 10
  pickaxes:
    item: DIAMOND_PICKAXE
    name: Кирки
    order: 50
    permission: bw.base
    lore:
    - Нажми, чтобы купить кирку
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 1
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 2
    - price:
      - type: GOLD_INGOT
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 3
  blocks:
    item: SANDSTONE
    name: Блоки
    order: 60
    permission: bw.base
    lore:
    - Нажми, чтобы купить блоки
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: SANDSTONE
        damage: 2
        amount: 2
    - price:
      - type: CLAY_BRICK
        amount: 7
      reward:
      - type: ENDER_STONE
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: IRON_BLOCK
    - price:
      - type: CLAY_BRICK
        amount: 15
      reward:
      - type: GLOWSTONE
        amount: 4
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GLASS
  usefulstuff:
    item: TNT
    name: Разное
    order: 70
    permission: bw.base
    lore:
    - Нажми, чтобы купить необычные предметы
    offers:
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: TNT
    - price:
      - type: GOLD_INGOT
      reward:
      - type: FLINT_AND_STEEL
    - price:
      - type: IRON_INGOT
      reward:
      - type: CHEST
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ENDER_CHEST
    - price:
      - type: IRON_INGOT
        amount: 15
      reward:
      - type: BLAZE_ROD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Спасательная платформа
          lore:
          - Защити себя от падения
          - с помощью спасательной платформы
    - price:
      - type: CLAY_BRICK
        amount: 64
      reward:
      - type: BRICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Защитная стена
          lore:
          - Используй защитную стену, чтобы
          - создать стену перед собой!
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: STRING
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Ловушка
          lore:
          - Если врах попадется ловушку, Вас проинформирует
          - и Ваш враг не сможет стабильно передвигарться.
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: SULPHUR
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Телепортационная пыль
          lore:
          - Когда Вы используете эту пыль,
          - Вы будете телепортированы на спавн команды в течении 6 секунд
          - 'Осторожно: Любое движение повлечет за собой прерыв телепортации'
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: MONSTER_EGG
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: ТНТ-Овца
          lore:
          - Используй ТНТ-Овцу, чтобы она подобралась
          - сзади к вашему враху и
          - взорвалась чеперз 8 секунд!
          internal: H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzkhNLWBgAAABt1TGHQAAAA==
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: COMPASS
  drinks:
    item: POTION
    name: Зелья
    order: 80
    permission: bw.base
    lore:
    - Нажми, чтобы купить зелья
    offers:
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: GOLD_INGOT
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
  donate:
    item: DIAMOND
    name: Донат
    order: 90
    permission: bw.donate
    lore:
    - Нажми, чтобы купить особые предметы для донатеров
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_BOOTS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
        amount: 10
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: CLAY_BRICK
        amount: 10
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
    - price:
      - type: CLAY_BRICK
      reward:
      - type: SANDSTONE
        damage: 2
        amount: 2
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GRILLED_PORK
        amount: 2
    - price:
      - type: GOLD_INGOT
        amount: 18
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 1
            ARROW_KNOCKBACK: 1
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ARROW
schema-version: 1
`

**Comment by tacosgogame** [comment]
shop:
  armor:
    item: DIAMOND_CHESTPLATE
    name: Броня
    order: 10
    permission: bw.base
    lore:
    - Нажми, чтобы купить броню
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_BOOTS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
        amount: 6
      - type: GOLD_INGOT
      reward:
      - type: IRON_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Магнитные сапоги
          lore:
          - Одень эти сапоги и получи 75%
          - шанс поглотить отдачу!
    - price:
      - type: IRON_INGOT
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 3
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Шлем
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
  swords:
    item: DIAMOND_SWORD
    name: Мечи
    order: 20
    permission: bw.base
    lore:
    - Нажми, чтобы купить меч
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 8
      reward:
      - type: STICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1
    - price:
      - type: IRON_INGOT
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 3
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
            KNOCKBACK: 1
    - price:
      - type: GOLD_INGOT
        amount: 15
      reward:
      - type: GOLD_AXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Топор бесконечности
          enchants:
            DAMAGE_ALL: 1
            DURABILITY: 1
            KNOCKBACK: 1
  bows:
    item: 261
    name: Луки
    order: 30
    permission: bw.base
    lore:
    - Нажми, чтобы купить лук
    offers:
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 7
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 13
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 2
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 16
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 15
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_KNOCKBACK: 1
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ARROW
  eat:
    item: GRILLED_PORK
    name: Еда
    order: 40
    permission: bw.base
    lore:
    - Нажми, чтобы купить провизию
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GRILLED_PORK
        amount: 2
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: GOLDEN_APPLE
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: BREAD
        amount: 10
  pickaxes:
    item: DIAMOND_PICKAXE
    name: Кирки
    order: 50
    permission: bw.base
    lore:
    - Нажми, чтобы купить кирку
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 1
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 2
    - price:
      - type: GOLD_INGOT
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 3
  blocks:
    item: SANDSTONE
    name: Блоки
    order: 60
    permission: bw.base
    lore:
    - Нажми, чтобы купить блоки
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: SANDSTONE
        damage: 2
        amount: 2
    - price:
      - type: CLAY_BRICK
        amount: 7
      reward:
      - type: ENDER_STONE
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: IRON_BLOCK
    - price:
      - type: CLAY_BRICK
        amount: 15
      reward:
      - type: GLOWSTONE
        amount: 4
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GLASS
  usefulstuff:
    item: TNT
    name: Разное
    order: 70
    permission: bw.base
    lore:
    - Нажми, чтобы купить необычные предметы
    offers:
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: TNT
    - price:
      - type: GOLD_INGOT
      reward:
      - type: FLINT_AND_STEEL
    - price:
      - type: IRON_INGOT
      reward:
      - type: CHEST
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ENDER_CHEST
    - price:
      - type: IRON_INGOT
        amount: 15
      reward:
      - type: BLAZE_ROD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Спасательная платформа
          lore:
          - Защити себя от падения
          - с помощью спасательной платформы
    - price:
      - type: CLAY_BRICK
        amount: 64
      reward:
      - type: BRICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Защитная стена
          lore:
          - Используй защитную стену, чтобы
          - создать стену перед собой!
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: STRING
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Ловушка
          lore:
          - Если врах попадется ловушку, Вас проинформирует
          - и Ваш враг не сможет стабильно передвигарться.
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: SULPHUR
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Телепортационная пыль
          lore:
          - Когда Вы используете эту пыль,
          - Вы будете телепортированы на спавн команды в течении 6 секунд
          - 'Осторожно: Любое движение повлечет за собой прерыв телепортации'
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: MONSTER_EGG
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: ТНТ-Овца
          lore:
          - Используй ТНТ-Овцу, чтобы она подобралась
          - сзади к вашему враху и
          - взорвалась чеперз 8 секунд!
          internal: H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzkhNLWBgAAABt1TGHQAAAA==
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: COMPASS
  drinks:
    item: POTION
    name: Зелья
    order: 80
    permission: bw.base
    lore:
    - Нажми, чтобы купить зелья
    offers:
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: GOLD_INGOT
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
  donate:
    item: DIAMOND
    name: Донат
    order: 90
    permission: bw.donate
    lore:
    - Нажми, чтобы купить особые предметы для донатеров
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_BOOTS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
        amount: 10
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: CLAY_BRICK
        amount: 10
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
    - price:
      - type: CLAY_BRICK
      reward:
      - type: SANDSTONE
        damage: 2
        amount: 2
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GRILLED_PORK
        amount: 2
    - price:
      - type: GOLD_INGOT
        amount: 18
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 1
            ARROW_KNOCKBACK: 1
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ARROW
schema-version: 1

**Comment by Granik24** [comment]
Just put those Russians names into 'put-it-here' and it will be fine. ;)

**Comment by sebastianbinder** [comment]
Any update on this, @tacosgogame ?
