### ISSUE TITLE
BedWars Shop issue

### ISSUE THREAD

**Issue by RealApple** [BedwarsRel/BedwarsRel#602]
I created an extensive bedwars shop but for some reason, it doesnt seem to load ingame. Please help!
`shop:
  armor:
    item: DIAMOND_CHESTPLATE
    name: Armour
    order: 10
    permission: bw.base
    lore:
    - Protect yourself with armor! Click here.
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_BOOTS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
        amount: 6
      - type: GOLD_INGOT
      reward:
      - type: IRON_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Magnet-Shoes
          lore:
          - Wear those shoes and have a 75%
          - chance of getting no knockback!
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 3
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 10
      reward:
      - type: DIAMOND_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 4
    - price:
      - type: DIAMOND
        amount: 10
      reward:
      - type: DIAMOND_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 4
    - price:
      - type: DIAMOND
        amount: 10
      reward:
      - type: DIAMOND_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 4
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 4
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: IRON_INGOT
        amount: 10
      reward:
      - type: IRON_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
            THORNS: 2
    - price:
      - type: IRON_INGOT
        amount: 10
      reward:
      - type: IRON_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
            THORNS: 2
    - price:
      - type: IRON_INGOT
        amount: 10
      reward:
      - type: IRON_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
            THORNS: 2
    - price:
      - type: IRON_INGOT
        amount: 10
      reward:
      - type: IRON_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
            THORNS: 2
  swords:
    item: DIAMOND_SWORD
    name: Swords
    order: 20
    permission: bw.base
    lore:
    - Click here to get sword for attacking your enemies
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 10
      reward:
      - type: STICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Cudgel
          enchants:
            KNOCKBACK: 3
    - price:
      - type: CLAY_BRICK
        amount: 20
      reward:
      - type: WOODEN_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Cudgel
          enchants:
            DAMAGE_ALL: 1
            KNOCKBACK: 2
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 3
            FIRE_ASPECT: 2
    - price:
      - type: IRON_INGOT
        amount: 10
      reward:
      - type: GOLD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 4
            FIRE_ASPECT: 2
            KNOCKBACK: 1
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
            FIRE_ASPECT: 1
            KNOCKBACK: 1
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 4
            FIRE_ASPECT: 2
            KNOCKBACK: 2
    - price:
      - type: GOLD_INGOT
        amount: 15
      reward:
      - type: IRON_AXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Warhammer
          enchants:
            DAMAGE_ALL: 5
            DURABILITY: 5
            KNOCKBACK: 5
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
            FIRE_ASPECT: 1
            KNOCKBACK: 1
    - price:
      - type: DIAMOND
        amount: 10
      reward:
      - type: DIAMOND_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 4
            FIRE_ASPECT: 2
            KNOCKBACK: 2
    - price:
      - type: DIAMOND
        amount: 15
      reward:
      - type: DIAMOND_AXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Splicer
          enchants:
            DAMAGE_ALL: 5
            DURABILITY: 4
            KNOCKBACK: 5
            FIRE_ASPECT: 2
  bows:
    item: 261
    name: Bows
    order: 30
    permission: bw.base
    lore:
    - Prove yourself as a marksman with these wonderful bows
    offers:
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 2
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 15
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 4
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
        amount: 20
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 4
            ARROW_KNOCKBACK: 2
            ARROW_FIRE: 2
            ARROW_INFINITE: 1
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ARROW
  eat:
    item: GRILLED_PORK
    name: Eat
    order: 40
    permission: bw.base
    lore:
    - Are you hungry? Get something to eat.
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GRILLED_PORK
        amount: 2
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: GOLDEN_APPLE
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: BREAD
        amount: 10
    - price:
      - type: GOLD_INGOT
        amount: 20
      reward:
      - type: GOLDEN_APPLE
        meta: null
  pickaxes:
    item: DIAMOND_PICKAXE
    name: Pickaxes
    order: 50
    permission: bw.base
    lore:
    - Destroy others blocks? Use these pickaxes.
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 1
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 2
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 1
            LOOT_BONUS_BLOCKS: 2
    - price:
      - type: IRON_INGOT
        amount: 10
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 3
            LOOT_BONUS_BLOCKS: 2
    - price:
      - type: GOLD_INGOT
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 3
            LOOT_BONUS_BLOCKS: 3
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: DIAMOND_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 3
            LOOT_BONUS_BLOCKS: 3
    - price:
      - type: DIAMOND
        amount: 10
      reward:
      - type: DIAMOND_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 5
            LOOT_BONUS_BLOCKS: 3
    - price:
      - type: DIAMOND
        amount: 20
      reward:
      - type: DIAMOND_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 10
            SILK_TOUCH: 1
            LOOT_BONUS_BLOCKS: 3
  blocks:
    item: SANDSTONE
    name: Blocks
    order: 60
    permission: bw.base
    lore:
    - Get to the others! Possible with blocks.
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: SANDSTONE
        damage: 2
        amount: 2
    - price:
      - type: CLAY_BRICK
        amount: 7
      reward:
      - type: ENDER_STONE
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: OBSIDIAN
    - price:
      - type: CLAY_BRICK
        amount: 15
      reward:
      - type: GLOWSTONE
        amount: 4
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GLASS
    - price:
      - type: GOLD_BRICK
        amount: 5
      reward:
      - type: BARRIER
  usefulstuff:
    item: TNT
    name: Useful Stuff
    order: 70
    permission: bw.base
    lore:
    - Looking for useful stuff? Here are some!
    offers:
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: TNT
    - price:
      - type: GOLD_INGOT
      reward:
      - type: FLINT_AND_STEEL
    - price:
      - type: IRON_INGOT
      reward:
      - type: CHEST
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ENDER_CHEST
    - price:
      - type: IRON_INGOT
        amount: 15
      reward:
      - type: BLAZE_ROD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Rescue Platform
          lore:
          - Protect yourself from falling into
          - void with a rescue platform
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: STRING
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Trap
          lore:
          - Get informed if an enemy steps on your trap
          - and your enemy won't be able to move properly.
    - price:
      - type: CLAY_BRICK
        amount: 64
      reward:
      - type: BRICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Protection Wall
          lore:
          - Use a protection wall to instantely
          - create a wall in front of you!
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: SULPHUR
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Warp Powder
          lore:
          - When using this powder you'll get
          - teleported to you spawn point within 6 seconds
          - 'Warning: Any movement will stop the process'
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: MONSTER_EGG
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: TNT-Sheep
          lore:
          - Use the TNT-Sheep! It will
          - walk towards your closest enemy
          - and explode within seconds!
          internal: H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzkhNLWBgAAABt1TGHQAAAA==
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: COMPASS
  drinks:
    item: POTION
    name: Drinks
    order: 80
    permission: bw.base
    lore:
    - Not enough? Use these potions and you'll feel better!
    offers:
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: GOLD_INGOT
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
schema-version: 1
`

**Comment by RealApple** [comment]
Version of BedwarsRel: 1.2.3 (not updating because the re
Version of Spigot: spigot-1.8.4-R0.1-SNAPSHOT-latest
Server Setup: Single Server
Installed plugins: BedwarsRel
BedwarsRel (1).jar
Essentials
Essentials-2.x-SNAPSHOT.jar
EssentialsChat-2.x-SNAPSHOT.jar
HolographicDisplays
HolographicDisplays.jar
PermissionsEx
PermissionsEx-1.23.4 (1).jar
PluginMetrics
ServerSigns
ServerSigns.jar
Updater
Vault
Vault.jar
WorldEdit
worldedit-bukkit-6.1.3.jar
WorldGuard
worldguard-6.1.2.jar
shop.yml: shop.yml
config.yml: config.yml
Errors on the Console: none

**Comment by sebastianbinder** [comment]
Unfortunately we cannot provide support for such old versions. In fact with Spigot 1.8.4 you can update to latest version of BedwarsRel

**Comment by RealApple** [comment]
Yes, i updated to 1.3.2 but it still doesnt seem to work. It seems as if i cant add new resources as a price... and many of these categories cant contain the amount of items in them. Please fix this.

**Comment by sebastianbinder** [comment]
We cannot fix anything before we know the error :) Please upload a properly formatted version of your shop.yml to pastebin and post the link here.

**Comment by sebastianbinder** [comment]
Any update on this?
