### ISSUE TITLE
generator level

### ISSUE THREAD

**Issue by dreamenemy** [BedwarsRel/BedwarsRel#603]
hello are you guys think add iron-gold-diamond genaraor level like cubecraft to plugin all players want this

**Comment by sebastianbinder** [comment]
Duplicate: https://github.com/BedwarsRel/BedwarsRel/issues/556

**Comment by djmagiko** [comment]
Hello look my friend please https://www.youtube.com/watch?v=FqrHy7XLjCc

it is your plugin but i dont see it version of your plugin please update please
thans my friend
