### ISSUE TITLE
Not change wait time if server full

### ISSUE THREAD

**Issue by caoli5288** [BedwarsRel/BedwarsRel#604]
You current do check in `GameLobbyCountdown.java` but it lag some often(one join and flash quit). I suggest do check every player join.

**Comment by sebastianbinder** [comment]
Hey @caoli5288 - don't really get the problem of the way it is handled right now. Could you describe it a little bit more detailed, please?

**Comment by caoli5288** [comment]
Do you know BungeeCloud? A plugin checked out one server and display on sign then player can click  to teleport to.
It query server info very often and will check out another server once current server is full.
Your plugin do full check 1 sec.
Sometimes It query a server full and check out another server but your plugin do not(one or more player flash quit). No more player will join this server and everyone have to wait very long time to start game.

**Comment by sebastianbinder** [comment]
Then "BungeeCloud" should check if the game has started instead of if the server is full. Still don't get the problem with BedwarsRel...

**Comment by sebastianbinder** [comment]
@caoli5288 any update on this?

**Comment by caoli5288** [comment]
@sebastianbinder No more. THX.
