### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MarekCz3ch** [BedwarsRel/BedwarsRel#605]
Hello, i own a minecraft server with Spigot on Version 1.10..
I installed this plugin and set up the map.Almost everything works perfectly, but i can't: Pick up the Bronze,Chat ( i see the messages in console ) and yeah.... :( No error shows up in the console.
Thank you, have a good day,
Regards, Marek

EDIT:

Version of BedwarsRel: 1.3.1
Version of Spigot: 1.9
Server Setup: Single Server
Installed plugins:Citizens,PlugMan,NoCheatPlus,WorldEdit,OldPvP,KingKits,BuildingGame,SkinsRestorer,PermissionsEX,Multiverse-Core,HolographicDisplays,ViaVersion,ColorMatch,SignColors,Essentials,MotdManager-Reloaded,Residence,ServerSigns,EssentialsSpawn,BedwarsRel,EssentialsChat,AuthMe
shop.yml: Original, i didn't configured anything.
config.yml: Original, i didn't configured anything.
Errors on the Console: No errors
Problem: When i run the bedwars, everything runs fine, but when i want to pick up bronze it doesn't really do anything. When i type to chat, i don't see my messages and friends in the game don't see them too. When i die, it just ports me to the spawn. But the Scoreboard is still there. Can you help me?

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by sebastianbinder** [comment]
First: Update BedwarsRel to latest version please.
Second: Remove any other plugin (except Multiverse-Core) and check if it works then.
If Yes: Third: Add the other plugins one by one, then you'll find out which plugin causes issues.
If No: Third: Tell us about it here :)

**Comment by sebastianbinder** [comment]
@MarekCz3ch Any update on this?
