### ISSUE TITLE
Join signs are empty

### ISSUE THREAD

**Issue by osnapitzkindle** [BedwarsRel/BedwarsRel#608]
I've setup a game and it works perfectly.
My problem is that when I put join signs on my main lobby they work but they don't show any text. The config file is still the default one, I haven't modified the join attribute.

Is this a bug or have I missed something?
Just for additional info, the first time I have set a sign up, Java threw a NullPointerException on GameJoinSign.java:100 probably because I didn't save the game.
Now I saved it and put another sign but still nothing.

Other plugins I have:
- multiverse-core
- permissionsbukkit
- skinsrestorer
- skript
- spawnjoin

**Comment by Granik24** [comment]
Any other informations? Spigot version? BWrel version?

**Comment by osnapitzkindle** [comment]
The latest version of the plugin and spigot for mc 1.10.2

Also noted that explosions may destroy the map

**Comment by Tibelian** [comment]
Hey, I can help you. I had the same error with another games. The signs are empty because you have a invalid spigot version. You can download the last versions and bugs fixed here: 
https://tcpr.ca/downloads/spigot

**Comment by osnapitzkindle** [comment]
Not all of the signs become empty by the way. Only when I put [bw] on it, letting the plugin modify them.
If you already understood what I said then I'll try it out

**Comment by Granik24** [comment]
Post here your way how you setup signs

**Comment by osnapitzkindle** [comment]
I have my lobby world and my game map, and when I set it up I just looked at the documentation for all the commands and used the commands I needed.
Then for the sign I pick a sign up (in creative mode if you want to know it) and placing it I write [bw]\n<gamename>
If the game name is not valid (e.g. It doesn't exist) it gives me an error as it should, just when the name is correct it goes ahead but leaving the sign empty

**Comment by Granik24** [comment]
What locale do you use for BWrel? Default one? (en)

**Comment by Tibelian** [comment]
Yeah I understand you. And I had the same error, just JOINING SIGNS ARE BUG/EMPTY.
And that is an error of your spigot/bukkit. Download the last updates form the link that I send you.
Just try it @osnapitzkindle

**Comment by sebastianbinder** [comment]
Problem solved?
