### ISSUE TITLE
Shop Error

### ISSUE THREAD

**Issue by Tibelian** [BedwarsRel/BedwarsRel#610]
I have the last version of this plugin and I found a bug, when you select the shop you can drag items to your own inventory without paying.

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by Tibelian** [comment]
shop:
  blocks:
    item: BRICK_BLOCK
    name: Bloques
    order: 10
    permission: bw.base
    lore:
    - Comprar bloques
    offers:
    - price:
      - type: IRON_INGOT
        amount: 1
      reward:
      - type: SANDSTONE
        amount: 2
    - price:
      - type: IRON_INGOT
        amount: 1
      reward:
      - type: GLASS
        amount: 1
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: GLOWSTONE
        amount: 1
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: OBSIDIAN
        amount: 1
  swords:
    item: IRON_SWORD
    name: Espadas
    order: 20
    permission: bw.base
    lore:
    - Comprar espadas
    offers:
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: WOOD_SWORD
        amount: 1
    - price:
      - type: IRON_INGOT
        amount: 32
      reward:
      - type: STONE_SWORD
        amount: 1
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_SWORD
        amount: 1
    - price:
      - type: DIAMOND
        amount: 12
      reward:
      - type: DIAMOND_SWORD
        amount: 1
  armor:
    item: IRON_CHESTPLATE
    name: Armaduras
    order: 30
    permission: bw.base
    lore:
    - Comprar armaduras
    offers:
    - price:
      - type: IRON_INGOT
      reward:
      - type: LEATHER_HELMET
    - price:
      - type: IRON_INGOT
      reward:
      - type: LEATHER_CHESTPLATE
    - price:
      - type: IRON_INGOT
      reward:
      - type: LEATHER_LEGGINGS
    - price:
      - type: IRON_INGOT
      reward:
      - type: LEATHER_BOOTS
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_HELMET
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_CHESTPLATE
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_LEGGINGS
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_BOOTS
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: IRON_HELMET
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: IRON_CHESTPLATE
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: IRON_LEGGINGS
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: IRON_BOOTS
  eat:
    item: CARROT
    name: Comida
    order: 40
    permission: bw.base
    lore:
    - Comprar comida.
    offers:
    - price:
      - type: IRON_INGOT
        amount: 1
      reward:
      - type: CARROT
        amount: 1
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: COOKED_BEEF
        amount: 1
    - price:
      - type: IRON_INGOT
        amount: 12
      reward:
      - type: CAKE
        amount: 1
    - price:
      - type: GOLD_INGOT
        amount: 2
      reward:
      - type: GOLDEN_APPLE
        amount: 1
    - price:
      - type: DIAMOND
        amount: 32
      reward:
      - type: GOLDEN_APPLE
        amount: 1
  pickaxes:
    item: IRON_PICKAXE
    name: Picos
    order: 50
    permission: bw.base
    lore:
    - Comprar picos.
    offers:
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: WOODEN_PICKAXE
        amount: 1
    - price:
      - type: IRON_INGOT
        amount: 20
      reward:
      - type: STONE_PICKAXE
        amount: 1
    - price:
      - type: GOLD_INGOT
        amount: 10
      reward:
      - type: IRON_PICKAXE
        amount: 1
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_PICKAXE
        amount: 1
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: DIAMOND_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 3
  bows:
    item: BOW
    name: Arcos
    order: 60
    permission: bw.base
    lore:
    - Comprar arcos
    offers:
    - price:
      - type: DIAMOND
        amount: 8
      reward:
      - type: BOW
        amount: 1
    - price:
      - type: DIAMOND
        amount: 12
      reward:
      - type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 1
    - price:
      - type: DIAMOND
        amount: 15
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_KNOCKBACK: 1
    - price:
      - type: DIAMOND
        amount: 32
      reward:
      - type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 2
            ARROW_KNOCKBACK: 1
schema-version: 1

**Comment by Tibelian** [comment]
I resolved that error, but now I have another error
I changed the shop and now the game dont start.
this is my shop.yml http://pastebin.com/wRqr5f8N

**Comment by sebastianbinder** [comment]
As I already told you, please provide any possible information mentioned in the wiki-entry linked above.

**Comment by Tibelian** [comment]
Version of BedwarsRel: 1.3.2

Version of Spigot: 1.10.2

Server Setup: Single Server

Installed plugins: Multiverse-Core, PEX, WorldEdit, WorldGuard, Vault, PerWorldInventory, ServerSigns, ActionHealth, ChangeSkin, AdvancedPortals, Citizens, CommandNPC, CustomJoinItems, GUIShop, Holograms, iConomy, Jobs, KingKits, Auras, LibsDisguises, PerWorldPlugins, ChestCommands, PlugMan, SonezSpawn. (and another minigames such SkyWars-MinigamesLIB, TNTRun, MobArena, War, BlockHunt...)

shop.yml-> http://pastebin.com/wRqr5f8N

config.yml-> http://pastebin.com/pJQwUZuR

Errors on the Console-> http://pastebin.com/ZJtKdjnA

Problem: I changed the shop and now the game dont start.

Sorry for do not provide the information before.

**Comment by Granik24** [comment]
Your problem is in resources. Create new spawner instead of editing Bronze.
  bronze:
    item: DIAMOND
    spawn-interval: 8500
    amount: 1
    spread: 1.0
    name: '&3Diamante'

here

**Comment by Tibelian** [comment]
Thank you for your help, but the game still buged.
When I try to force start it just say ingame this ' GAME STARTING...'
And in the console an error.
But if I put again the original shop.yml the game start and no error appear on the console.

**Comment by Granik24** [comment]
Send me that error. :)

**Comment by Tibelian** [comment]
http://pastebin.com/6gAnY54i

**Comment by Granik24** [comment]
http://hastebin.com/poxemukefa.yml
you don't have amounts setted yet

**Comment by sebastianbinder** [comment]
The missing amounts should not be a problem as they are just "1" when not set. The error simply says there is a problem with you shop.yml which means you need to debug your file. Backup a copy of your shop.yml somewhere and then remove all the categories and add them one by one and check when the shop exactly stops working. Then you can debug the single items in the category as well. That's the way to find out which items causes the error.

**Comment by Tibelian** [comment]
Oh, thank you, now the game start with the dev build with my shop.yml

**Comment by sebastianbinder** [comment]
On the log file now you should see which item caused the error.

**Comment by Tibelian** [comment]
http://pastebin.com/QaFmQkhP

**Comment by LazoYoung** [comment]
You can append damage: 1 to make the golden apple enchanted(blinking)
below the type: GOLDEN_APPLE. Sorry for late response.
