### ISSUE TITLE
Teams.

### ISSUE THREAD

**Issue by TheIntelloBox** [BedwarsRel/BedwarsRel#638]
Hello,

I have a big problem with the teams.

I have a map with a maximum of players of 16, and for example, 4 players can be in the purple team, and only one person in the Green Team. 
Can you add anything so that the selection of the team is automatic so that it is fairer?

Thanks,
TheIntelloBox.

**Comment by sebastianbinder** [comment]
https://github.com/BedwarsRel/BedwarsRel/blob/master/src/main/resources/config.yml#L43
