### ISSUE TITLE
Problem with Villager

### ISSUE THREAD

**Issue by TheIntelloBox** [BedwarsRel/BedwarsRel#639]
Hello,

Look at my screen, and my config, and I you will see that my bows haven't got enchantment, whereas in the config they have an enchantment. It's the same problem with Chainmail_Helmet...

Thanks to help me to fix it,
TheIntelloBox.

**Comment by TheIntelloBox** [comment]
Please. :(

**Comment by TheIntelloBox** [comment]
Up please. :(

**Comment by EnderBoyHUN** [comment]
Not exist: UNBREAKING, EFFICIENCY, ...

_DURABILITY = UNBREAKING_ 
(If I know right)

Here is a list of enchantments: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
