### ISSUE TITLE
GOLDEN_SWORD Funktioniert nicht als item für eine Kategorie im shop.

### ISSUE THREAD

**Issue by Bingbraten** [BedwarsRel/BedwarsRel#646]
# so gehts    

  Schwerter:
    item: 283
    name: '&cSchwerter'
    order: 40
    permission: bw.base
    lore:
    - §7Greife deine Gegner an und schubs sie runter

# so nicht

  Schwerter:
    item: GOLDEN_SWORD
    name: '&cSchwerter'
    order: 40
    permission: bw.base
    lore:
    - §7Greife deine Gegner an und schubs sie runter

# UND

die wooden pickaxe kann man im shop nicht anbieten habe WOODEN_PICKAXE und die id benutzt geht beides nicht

[BedWars] Couldn't parse item in category "&aSpitzhacken": {price=[{type=CLAY_BRICK, amount=4}], reward=[{type=WOODEN_PICKAXE, meta=UNSPECIFIC_META:{meta-type=UNSPECIFIC, enchants={DURABILITY=1}}}]}

Meine ganze shop.yml: http://pastebin.com/pxQ8N6hS

### Ich benutze BedwarsREL Version 1.3.3, Spigot/Bungeecord 1.10.2, Java Build 1.8.0_101-b13

**Comment by sebastianbinder** [comment]
Heißt ja auch `GOLD_SWORD` und `WOOD_PICKAXE`...
