### ISSUE TITLE
Schild zeigt nix!!

### ISSUE THREAD

**Issue by ZockerWelt** [BedwarsRel/BedwarsRel#660]
Wenn ich ein Schild für ein Spiel erstelle kann man zwar joinen und alles geht wie geölt aber das Schild zeigt nix an!! Ich benutze Spigot-Server  Plugin ver.1.3.3. Bitte um Hilfe! :)

**Comment by sebastianbinder** [comment]
Hi. Wir bräuchten an dieser Stelle mehr Details von dir. Also schau doch bitte mal auf https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue und lass uns so viel wie möglich über dein Setup wissen.

**Comment by sebastianbinder** [comment]
Neuigkeiten @ZockerWelt ?
