### ISSUE TITLE
LAG SPIKES - ERRORS

### ISSUE THREAD

**Issue by GlobooX** [BedwarsRel/BedwarsRel#663]
### General Information
- **Version of BedwarsRel**:  latest
- **Version of Spigot**: git-Spigot-e0e1771-5e5cf84 (MC: 1.10.2)
- **Server Setup**: Single Server
- **Installed plugins**: http://screenshot.sh/mMb2nFXSwYgFv
- **shop.yml**: http://pastebin.com/3yLwEGzQ
- **config.yml**:  http://pastebin.com/LJHMcqk6
- **Errors on the Console**: http://pastebin.com/LhsRJJEq, http://pastebin.com/0tkuRcPD, http://pastebin.com/0rJdSHRg (every 1 second when countdown is running in lobby i have this error then arena is not starting, player is not teleporting to arena)

Error 2 MOST IMPORTANT: Sometimes when arena is end, players is not teleporting to lobby... and when player leave or DEATH too. (http://pastebin.com/XKVBEN4W, http://pastebin.com/maTKZy0c)
Look's like player is still in arena but can join to other arena.

SORRY for my english..

### Problem
LAG SPIKES, Arena sometimes not starting
Timings: https://timings.spigotmc.org/?url=lakuwuwede

**Comment by sebastianbinder** [comment]
First of all, please remove any plugin except BedwarsRel and its dependencies. Then try again an tell us if those errors are still there. That's the first thing we need to check on.

**Comment by GlobooX** [comment]
I have the same plugins like on BedWars version 2-3 months ago..
But.. ok.. i will check this.

**Comment by GlobooX** [comment]
EDIT: It is not from other plugins..
BedWars working perfect over 10-20 minutes and then is bugging wiht errors in my post #1.
Here is another error log when i stop bugged arena: http://pastebin.com/aztMpJeQ

**Comment by sebastianbinder** [comment]
Is there any error showing up on player join?

**Comment by GlobooX** [comment]
When player join arena or server?

**Comment by sebastianbinder** [comment]
After clicking on a sign or typing /bw join

**Comment by GlobooX** [comment]
Nope, there is not any errors on this event.

**Comment by GlobooX** [comment]
I have to let important plugins like Essentials, WorldEdit, WorldGurd cuz players can destroy my spawn.

**Comment by sebastianbinder** [comment]
Then do it on one of your test servers.

**Comment by GlobooX** [comment]
Ok, first i setup arena again. When bug be still i do what do You want :)

**Comment by GlobooX** [comment]
Nope... when i set 2 Arenas bug still is.. ;/
I have to do what You want..

**Comment by GlobooX** [comment]
Problem fixed..  Delete RandomSK was solution
