### ISSUE TITLE
Shop Price BUG

### ISSUE THREAD

**Issue by GlobooX** [BedwarsRel/BedwarsRel#664]
Hello, yesterday i found "bug". In new item shop, this issue is only in potion category, in config everything is okay, also ingame shows normal prize iron, gold... But if you click they accept only 3 iron per piece, does not matter whar price is in config, first potion is for 3 iron, that should be global price ? i do not see any mistake in config. Sorry about pastecode, it not allowed me to upload zip file.

(TEXT COPIED FROM OTHER ISSUE FOR BUMP, BECOUSE THIS BUG IS IMPORTANT)

**Comment by sebastianbinder** [comment]
We are aware of this issue - no need to duplicate
