### ISSUE TITLE
If I create a Sign for joining a Game it didn't show something

### ISSUE THREAD

**Issue by xMichelx** [BedwarsRel/BedwarsRel#666]
If I create a sign it works but it didn't show anything so you can't see Which Map/game or how many players are in the lobby. Please fix that it's a very cool plugin.

I use Craftbukkit for Minecraftversion 1.10.2 and BWReloaded 1.3.3.

Thanks

**Comment by sebastianbinder** [comment]
Are you using ViaVersion and joining with a 1.9 client? I know about some people experiencing issues when having this setup.

**Comment by sebastianbinder** [comment]
Any news @xMichelx ?
