### ISSUE TITLE
How is that beds are only breakable with the TNT ?

### ISSUE THREAD

**Issue by TheIntelloBox** [BedwarsRel/BedwarsRel#667]
Hello,

I want that beds are only breakable with TNT but I don't see this option in the config.yml.
Could you help me ? :D 

Thanks,
TheIntelloBox. :D

**Comment by TheIntelloBox** [comment]
Up. :D

**Comment by sebastianbinder** [comment]
Feel free to fork the repositor, implement it yourself and open a pull request if you need it that fast.

**Comment by TheIntelloBox** [comment]
Could you, please add it as a feature ? :( It's very important for many owners ! 💃

**Comment by sebastianbinder** [comment]
We recently talked about this in our dev-team and at the moment it seems like we won't implement this. There has never been a request like this before ("It's very important for many owners") and we don't think this is a "Bedwars"-feature.

**Comment by TheIntelloBox** [comment]
Oh okay, as you wish. :)
