### ISSUE TITLE
Road to Minecraft 1.11 - Release BedwarsRel 1.3.4

### ISSUE THREAD

**Issue by sebastianbinder** [BedwarsRel/BedwarsRel#675]
# Roadmap
- Wed, 16/11/2016, no more new features, creating branch `release-1.3.4`
- testing of branch `release-1.3.4`
- Thu, 17/11/2016, CraftBukkit and Spigot 1.11 get released, implementing changes for 1.11
- Sat, 19/11/2016, testing of branch `release-1.3.4` with the 1.11 changes
- Mon, 21/11/2016, or Tue, 22/11/2016, release BedwarsRel 1.3.4

# Changelog (WIP)

# Features

__1.11 Compatibility__
This version of BedwarsRel provides compatibility with Minecraft 1.11. Yes, this plugin is now compatible with four (4!) different Minecraft versions. You can use it on a server running 1.8.X, 1.9.X, 1.10.X or 1.11. But please note that it is very hard to support, develop and test for four different Minecraft versions. There are still roundabout 50% of servers running BedwarsRel in an 1.8.X environment. So why not updating your server to latest Minecraft, so that we can drop support for older versions in one of the next releases?

__Arrow Blocker__
We added a new Special Item "[Arrow Blocker](https://github.com/BedwarsRel/BedwarsRel/wiki/shop.yml#list-of-bedwarsrels-special-items)" for you.

__Debug Data__
A new command `/bw debugpaste` has been introduced. Using this command collects some data of your setup, uploads it to Pastebin and then returns a link that you can provide if we or any other person in the BedwarsRel community need some more information for helping you with your problem.

__Better translations__
From the previous release you already know, that BedwarsRel now integrates with the translation platform "[Crowdin](https://www.crowdin.com)". Of course we updated some translations thanks to the great translators we have in the BedwarsRel community. Wanna have the plugin in your language? Head over to [the project here](https://crowdin.com/project/bedwarsrel/) and propose some translations. To make use of our completely new translation system, please delete the ``BedwarsRel/locale`` directory once if it's still there from older releases (as long as you have not modified the translations). Since people are asking again and again: If you want to use your own translation, please have a look on our [wiki](https://github.com/BedwarsRel/BedwarsRel/wiki/Localization) - wasn't that hard to find, right?

# How To Update
This update should work out of box, just replace the ``.jar``. But as always, you should backup your old configuration-files and check if everything is fine with the config after updating.

# Release Candidate

Download [here](https://2410-32877020-gh.circle-artifacts.com/0/tmp/circle-artifacts.MiLpvaj/BedwarsRel-1.3.4-SNAPSHOT.jar) for testing.

**Comment by TheIntelloBox** [comment]
Perfect. What are the feature of the new version of Bedwars Rel ?

**Comment by sebastianbinder** [comment]
You'll find out as soon as it is released.

**Comment by TheIntelloBox** [comment]
Okay good.

**Comment by Sollembum78** [comment]
It may be wrong place to write, but want to ask, how to add colored blocks to shop? Or even better, maybe adding colored glass, wool, clay will sell with team color?

**Comment by sebastianbinder** [comment]
@Sollembum78 You are right. An issue tracker or this issue in general is the wrong place for that question. I could answer it, but then people would starting messing with off topic questions on every issue. Ask on SpigotMC.org, ask on Gitter or simply search the issues here for colored blocks (which gives you an answer as well).
