### ISSUE TITLE
Sources for lvl store

### ISSUE THREAD

**Issue by NikichSuperGames** [BedwarsRel/BedwarsRel#683]
Hello!
  Can you give Bedwars source plugin for me to add to it lvl shop and a selection of cards.
PS if you want then you can then put it in the shared

**Comment by sebastianbinder** [comment]
Please speak proper English, then we might be able to help you.

**Comment by NikichSuperGames** [comment]
I'm sorry ... Can you please give the plugin source code for me to add lvl shop and a selection of maps

**Comment by sebastianbinder** [comment]
Obviously you don't understand the sense of Git, GitHub and SCM in general…
