### ISSUE TITLE
Upgrade http links to https

### ISSUE THREAD

**Issue by ypid** [BedwarsRel/BedwarsRel#693]
GitHub automatically redirects to HTTPS and they even have HSTS deployed, just no preloading.

Can you check http links and upgrade them to https?

Places I noticed:

* Repo description: https://github.com/BedwarsRel/BedwarsRel
* Repo description: https://github.com/BedwarsRel/bedwarsrel.github.io
* What is the URL for the project: https://bestpractices.coreinfrastructure.org/projects/525

**Comment by sebastianbinder** [comment]
Updated.
