### ISSUE TITLE
Suggestion - disable collision for teammates.

### ISSUE THREAD

**Issue by Sollembum78** [BedwarsRel/BedwarsRel#701]
Sometimes your teammates push your off bridges, so would be nice to have option to disable player collision on 1.9+

As I know it's possible using scoreboards, but since BWR uses scoreboards, messing with the default one (built in) can cause problems.

**Comment by sebastianbinder** [comment]
We've been talking about this in our dev team at the time of the 1.9 release and we decided to not implement any default minecraft behavior changes. The player collision is part of having a good tactic in gameplay.
