### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by raunak114** [BedwarsRel/BedwarsRel#704]
When you start a game, this error shows up (didnt happen today morning):
`[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:40 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:40 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:40 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
17.12 18:06:41 [Server] WARN Task #187 for BedwarsRel v1.3.4 generated an exception
17.12 18:06:41 [Server] INFO java.lang.IllegalStateException: Unregistered scoreboard component
17.12 18:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.getEntries(CraftTeam.java:121) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Team.getPlayers(Team.java:169) ~[?:?]
17.12 18:06:41 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Game.getTeamPlayers(Game.java:1474) ~[?:?]
17.12 18:06:41 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Shop.Specials.Tracker$1.run(Tracker.java:57) ~[?:?]
17.12 18:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
17.12 18:06:41 [Server] WARN Task #246 for BedwarsRel v1.3.4 generated an exception
17.12 18:06:41 [Server] INFO java.lang.IllegalStateException: Unregistered scoreboard component
17.12 18:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.getEntries(CraftTeam.java:121) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Team.getPlayers(Team.java:169) ~[?:?]
17.12 18:06:41 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Game.getPlayers(Game.java:1486) ~[?:?]
17.12 18:06:41 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Game.updateScoreboardTimer(Game.java:1857) ~[?:?]
17.12 18:06:41 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Game.access$000(Game.java:60) ~[?:?]
17.12 18:06:41 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Game$7.run(Game.java:1940) ~[?:?]
17.12 18:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
17.12 18:06:42 [Server] WARN Task #187 for BedwarsRel v1.3.4 generated an exception
17.12 18:06:42 [Server] INFO java.lang.IllegalStateException: Unregistered scoreboard component
17.12 18:06:42 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:42 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.getEntries(CraftTeam.java:121) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4507d99]
17.12 18:06:42 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Team.getPlayers(Team.java:169) ~[?:?]
17.12 18:06:42 [Server] INFO at io.github.bedwarsrel.BedwarsRel.Game.Game.getTeamPlayers(Game.java:1474) ~[?:?]`

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please paste the output of `/bw debugpaste` here to let us know more about your setup.

**Comment by sebastianbinder** [comment]
Any update on this?
