### ISSUE TITLE
Break Bed with hand

### ISSUE THREAD

**Issue by Tristiisch74** [BedwarsRel/BedwarsRel#709]
Can you add an option to prevent breaking ennemy bed with hand ?
With blacklist block it's doesn't work.

Thanks,

**Comment by sebastianbinder** [comment]
That's not in the original sense of bedwars. Destroying the bed by hand is the "standard".

**Comment by Tristiisch74** [comment]
I don't ask you if it's the original or not ...

**Comment by Arkazium** [comment]
It's too bad for french players :/
