### ISSUE TITLE
Being able to use join signs thru servers.

### ISSUE THREAD

**Issue by xidjn** [BedwarsRel/BedwarsRel#710]
Im not sure if this feature is in the plugin or not but i think you should be able to join thru a sign from server to server. If there is any videos or explanations on it please let me know because this problem has been annoying me alot. There also is a problem with when you die. When others die they get kicked for flying for no reason. If you know the issue let me know please. -xIDJN

**Comment by sebastianbinder** [comment]
Right now there is no feature like that, because there are already enough plugins handling that (e.g. TeleportSigns).

**Comment by sebastianbinder** [comment]
Because of the other issue: This seems like a problem with your anti-cheat or another plugin.
