### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by jannis1198** [BedwarsRel/BedwarsRel#720]
Version of BedwarsRel: 1.3.3
Version of Spigot: 1.10.2
Bungeecord
Installed plugins:  BedwarsRel, Multiverse-Core, PermissionsEx, Vault, worldedit, worldguard
Error in Console: http://pastebin.com/B2ZKVXxg
Problem:
Everytime the Server restarts after a game has finished, i get an error and the plugin won't load. Then i have to reupload the plugin. After that everything works fine until the next time the Server restarts.

**Comment by sebastianbinder** [comment]
First of all, use version 1.3.4 please.
Regarding your problem: Seems like the file is corrupted. This may have happened when down- or uploading the jarfile.

**Comment by sebastianbinder** [comment]
Any update on this?
