### ISSUE TITLE
Potions has always the price of the first potion

### ISSUE THREAD

**Issue by Kaskadee** [BedwarsRel/BedwarsRel#722]
I'm currently trying to setup potions in the shop and the problem is, that the price for all potion is always the price for the first item. (Using BedwarsRel 1.3.4 and Spigot 1.8.8)

Currently I have four Potions:

- Potion of Healing I (3 iron ingots)
- Potion of Healing II (6 iron ingots)
- Potion of Swiftness I (8 iron ingots)
- Potion of Strength I (6 gold ingots)

The shop says, that the potion of strength costs 6 gold ingots but it takes 3 iron ingots from my inventory. (same for all other potions).

shop.yml: http://pastebin.com/DwcP6ufX

http://imgur.com/a/lgHza

There no errors in console.

**Comment by sebastianbinder** [comment]
Maybe setting a display name for the potion helps. There is a known problem with comparing potions, but I don't really know how to fix it. Please check if setting a display name for those potions helps and give us some feedback again.

**Comment by KaskadekingDE** [comment]
Doesn't work :/

**Comment by ScuroK** [comment]
@sebastianbinder i have the same issue. Can you try to fix it pls? <3

**Comment by ScuroK** [comment]
Not so long ago there was a change on the potion data in Minecraft. many plugins had to adjust to make potions work again. For example MobArena. 
Maybe you should ask them.

**Comment by sebastianbinder** [comment]
Here's the latest dev-build including your fix: https://3078-32877020-gh.circle-artifacts.com/0/artifacts/BedwarsRel-1.3.5-SNAPSHOT.jar
