### ISSUE TITLE
Invicible villagers

### ISSUE THREAD

**Issue by ErkSterk** [BedwarsRel/BedwarsRel#725]
When a player dies the villager appeares invicible and cannot be clicked even tho we can hear it, im using version 1.3.4 with no edited shop or config

**Comment by ErkePannekake** [comment]
also server running 1.8

**Comment by r2d2c** [comment]
yes, i know this issue too.

**Comment by sebastianbinder** [comment]
Hi. Please try to remove any other plugin except BedwarsRel's dependencies and try again. Most of the times there is a compatibility issue caused by other plugins.

**Comment by ErkePannekake** [comment]
i tried this with only these plugins: Multiverse-Core, ProtocolLib, HolographicDisplays, and ofc bedwarsRel,
i also tried without holograms but still the villager is gone.

**Comment by ErkePannekake** [comment]
BUMP

**Comment by ErkePannekake** [comment]
BUMP

**Comment by ErkePannekake** [comment]
BUMP

**Comment by ErkePannekake** [comment]
BUMP
