### ISSUE TITLE
Armor saving

### ISSUE THREAD

**Issue by Skilzar** [BedwarsRel/BedwarsRel#729]
Hello! :)
I want to offer the player did not disappear armor if for example he fell.
At the beginning of the game in his leather armor the color of his team.
In villagers can buy chain-mail armor of iron armor and diamond armor.
Example: https://youtu.be/IHiQ6tVKWUk
It saves time

**Comment by sebastianbinder** [comment]
Please use proper English language for describing this feature request. I'm not able to understand anything here.

**Comment by Skilzar** [comment]
I want to offer the player did not disappear armor if for example he fell.
At the beginning of the game in his leather armor the color of his team.
In villagers can buy chain-mail armor of iron armor and diamond armor.
Example: https://youtu.be/IHiQ6tVKWUk

**Comment by sebastianbinder** [comment]
@Skilzar this can easily be achieved with a custom little plugin which listens to the `PlayerDeathEvent`. Just ask your server's developer for help. He can use BedwarsRel's [GameManager](https://github.com/BedwarsRel/BedwarsRel/blob/master/src/main/java/io/github/bedwarsrel/BedwarsRel/Game/GameManager.java) for checking if the player who died is in a Bedwars game.
There have been requests about implementing kits (your feature is kind of a kit) and all of us three developers don't see having kits as a real original Bedwars feature, so we decided there won't be an implementation of kits on our side.
