### ISSUE TITLE
SLF4J Console Error

### ISSUE THREAD

**Issue by doitliketyler** [BedwarsRel/BedwarsRel#730]
Bedwars Version: 1.3.4
Server Version: Paper Spigot 1.11.2
Server Setup: Single Server
Console Error: http://pastebin.com/TJjQWi4K
Problem: A SLF4J console error shows up after plugin enable.

Thoughts?

**Comment by sgdc3** [comment]
It's just a warning, bedwars isn't including the required libraries to show the log of some depenency using slf4j logger.

**Comment by sebastianbinder** [comment]
@sgdc3 thanks for explaining :)
