### ISSUE TITLE
BedwarsGameBedDestroyEvent

### ISSUE THREAD

**Issue by darkspive** [BedwarsRel/BedwarsRel#732]
Please add BedwarsGameBedDestroyEvent

**Comment by sebastianbinder** [comment]
Hi @darkspive,
I just added a `BedwarsTargetBlockDestroyedEvent`. Check out on the dev-build on https://3065-32877020-gh.circle-artifacts.com/0/artifacts/BedwarsRel-1.3.5-SNAPSHOT.jar

**Comment by darkspive** [comment]
Thanks
