### ISSUE TITLE
Missing getter methods in multiple classes

### ISSUE THREAD

**Issue by akashaggarwal7** [BedwarsRel/BedwarsRel#735]
The Main.java class is missing that method. Is this a mistake or is there a reason behind it? I'm assuming if its a mistake then only the bugsnag object needs to be returned. TIA

**Comment by akashaggarwal7** [comment]
Many more getter methods are actually not available in different classes. For example the io.github.bedwarsrel.BedwarsRel.Game class is missing getState(), getRegion(), getName() etc. I didn't even look into other classes yet. Is the latest commit on master a bad commit or am I doing something wrong here? I'm using IntelliJ idea and I cloned the project to add more custom features to it.

**Comment by sebastianbinder** [comment]
Is the Lombok Plugin installed in your IntelliJ?

**Comment by akashaggarwal7** [comment]
Thank you, I feel like an idiot for not reading the README page since I was so excited in getting to modify the plugin.
