### ISSUE TITLE
MySQL and Bungeecord

### ISSUE THREAD

**Issue by MaluaK** [BedwarsRel/BedwarsRel#749]
This thread is in German and also in English. First german!

German Introduktion:
Hallo Ihr Bedwars Meister :)

Ich habe euer Plugin auf meinem Netzwerk installiert.
Soweit es soll funktioniert es auch, jedoch funktioniert nicht alles.
Datenbank MySQL funktioniert NICHT!
- Datenbank eingegeben
- Config gespeichert
- Hochgeladen
- Nicht verbunden
- Kein Error

Bedwarsversion: BedwarsRel-1.3.4.jar
Spigotversion: 1.11.2 

Und in der Lobby kann ich KEIN Schild erstellen damit die User dieser Runde/Spiel beitreten können.
Momentan funktionieren diese Funktionen nicht.
In der Konsole werden keine fehler angezeigt.
Weiterhin stehen nirgends Informationen wie man einen ,,Shop-Villager" erstellt. 

English Introduktion:
I installed your plugin on my network.
As far as it works it also works, however does not everything.
Database MySQL is NOT working!
Database
- Config
- Uploaded
- Not connected
- No error

Bedwars version: BedwarsRel-1.3.4.jar
Spigot version: 1.11.2

And in the lobby I can not create a shield so the users can join this round / game.
Currently, these functions do not work.
No errors are displayed in the console.
Furthermore, there is no information about how to create a "shop-villager".

Hope you help me to fix this problems as fast as you can.

Thank you much.
If you have Questions join the Teamspeak: ts.maluak.de:10161 

_____________________________

MaluaK
MaluaK Community Team
Server: mc.maluak.de
Version: 1.11.2
(Still whitelisted Beta in planning)

**Comment by sebastianbinder** [comment]
> Database MySQL is NOT working!

Cannot help you out if there is no error being displayed.

> And in the lobby I can not create a shield so the users can join this round / game.

There is no sign support for Bungeecord setups. There are several plugins like `TeleportSigns` that can handle connecting to a Bedwars server in your Bungeecord setup.

> Furthermore, there is no information about how to create a "shop-villager".

Just spawn a villager on your map. Configuration is being explained on https://github.com/BedwarsRel/BedwarsRel/wiki/shop.yml

**Comment by MaluaK** [comment]
So could you give me more infos about the database to Support MySQL?

**Comment by sebastianbinder** [comment]
What kind of information do you need?

**Comment by MaluaK** [comment]
How i can Connect to MySQL Database. this config don't work. 
So if i find a Error I Send you as fast as i can.

**Comment by sebastianbinder** [comment]
Is this issue still valid?
