### ISSUE TITLE
Error: Locale not found

### ISSUE THREAD

**Issue by ImCydex** [BedwarsRel/BedwarsRel#752]
First off I want do say that i already read through the other posts, but couldn't find any solution to this problem.
When i load BedwarsRel it tells me that the locale was not found, the chosen locale file has the same name as the one chosen in the config, but still it doesn't work.

Config: https://pastebin.com/xiz0tRn3

Locale: https://pastebin.com/qJpNErPy

**Comment by sebastianbinder** [comment]
A list of all supported locales can be found on https://github.com/BedwarsRel/BedwarsRel/tree/master/src/main/resources/locale
If you want to use custom localization, please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/Localization
