### ISSUE TITLE
Flying for Trolling

### ISSUE THREAD

**Issue by michihupf** [BedwarsRel/BedwarsRel#753]
I need the permission so that I can Fly in a BedWars-Round. And why the hell are the blocks which I break with a plugin by me with block.breakNaturally(); not respawning when the round starts again???

**Comment by sebastianbinder** [comment]
> Flying for Trolling - I need the permission so that I can Fly in a BedWars-Round

We won't change anything in the plugin which makes it possible for players to troll other people. BedwarsRel is a professional Bedwars plugin for servers and we don't want that other people annoy players when playing with our plugin.

> And why the hell are the blocks which I break with a plugin by me with block.breakNaturally(); not respawning when the round starts again???

Why the hell should the plugin register block changes not being changed by players? BedwarsRel tracks every block change - feel free to rewrite your plugin, keep track of the blocks yourself and listen to the corresponding event to check if the game is over and then restore those blocks.
