### ISSUE TITLE
Bedwars error 

### ISSUE THREAD

**Issue by zr120cat** [BedwarsRel/BedwarsRel#757]
BedwarsRel version: 1.3.4
Spigot version: 1.9.2
Server: Single Server
Installed Plugins: [http://imgur.com/a/x6ZT0]
Shop.yml: [https://pastebin.com/1Jq0u0Yd]
Config.yml: [https://pastebin.com/Ukpb4njJ]
Errors in console: [https://pastebin.com/fknz1YS3]
Problem
When the game starts, it all works right. If I click start game now, it glitches. If I wait for the time, I dont get put on a team. If I choose a team the countdown clock in lobby stops counting. When I spawn (If it works) I cant pick up blocks like the iron and gold and it just doesn't look right!

**Comment by sebastianbinder** [comment]
Could you please try again with removing every plugin except BedwarsRel and its dependencies? Just want to make sure that this is not a compatibility issue. Please give me feedback about your test result.

**Comment by zr120cat** [comment]
I tried the plugin on a custom server (not main server) and it worked. I'm gonna remove all my plugins then slowly add them to see which one is the one causing problems.

**Comment by zr120cat** [comment]
Do you know if a protocol hack would cause the error. If so, then I'll have to make tough decisions

**Comment by sebastianbinder** [comment]
Plugins like ViaVersion or ProtocolSupport are working fine on my own server.

**Comment by zr120cat** [comment]
I found out the issue! It was a 1.8 simulator. 

I also tried the game and I like it. Can you possibly add a fireball to make the game more competitive and tnt that ignites on place. If you can't do these then I am wondering if my dev can add it in easily

**Comment by sebastianbinder** [comment]
Fireball: #728
