### ISSUE TITLE
Cannot Build in Arena

### ISSUE THREAD

**Issue by Jimjimkewl** [BedwarsRel/BedwarsRel#767]
1. The players cannot build/break in the arena.

2. The player's inventory before joining will be gone after the game, it doesn't save.

If you know any solution of the problem pls help ;-( Thank you

**Comment by sebastianbinder** [comment]
1. Please have a look on our FAQ

2. Please check if this error persists without any other plugin.

**Comment by Jimjimkewl** [comment]
1. I saw the solution, i set spawn protection to 0 but still I couldnt build. I checked the regions in the world but theres no region.

2. Ill try it later but i have Multiverse-Inventories

**Comment by sebastianbinder** [comment]
1. Then I need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

2. Any update on this?
