### ISSUE TITLE
How to make an "enchanted_book"

### ISSUE THREAD

**Issue by ywtz** [BedwarsRel/BedwarsRel#768]
Hello author,
I have an issue about how to make an enchanted_book.
If I use the way like that wiki mentioned,in minecraft it cannot used on anvil,so my weapon cannot be enchanted by anvil,can you help me solve this problem?
plz send me the example by the link in"pastebin.com",thank you.

(Probably I have some grammar mistakes)

**Comment by brainscript** [comment]
@ywtz Maybe you could post your current config file. Your problem might lie in the names of the items and enchantments which you can look up [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) and [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html). You always have to keep in mind that this is a Spigot plugin and not a Minecraft plugin and it, therefore, uses other names.

**Comment by ywtz** [comment]
Yes i'm use the spigot server i say my config  just imitate the wiki of shop.yml,i means can you give a example about the enchanted book？

**Comment by ywtz** [comment]
can you give me your email in order to show you some screenshots.

**Comment by brainscript** [comment]
Just copy [this example](https://github.com/BedwarsRel/BedwarsRel/wiki/shop.yml#enchanted-items) into your `shop.yml` and replace `IRON_SWORD` with `ENCHANTED_BOOK` and put the wanted enchantments into the `enchants` section, like this:

    - reward:
      - type: ENCHANTED_BOOK
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
      price:
      - type: IRON_INGOT
        amount: 2

If you want to send screenshots upload them here on GitHub, click the "selecting them" link at the bottom of the text area or drag them into it.

**Comment by ywtz** [comment]
Thanks for your amazing review at first,and i'll try it tomorrow,plz don't close this issue.

**Comment by sebastianbinder** [comment]
Any update on this?

@brainscript: Thank you!
