### ISSUE TITLE
Adding party and clanwars

### ISSUE THREAD

**Issue by ErkePannekake** [BedwarsRel/BedwarsRel#769]
Hi it would be cool if you added a party fuction and a clanwar function in the plugin. like if i join a map all my party members joined as well and if i join clanwars a menu pop up to choose the half of the map max and join a queue until another guild come and choose other members then the game starts.

**Comment by sebastianbinder** [comment]
This plugin offers Bedwars as it is. Features like parties oder queues can easily be managed by other plugins. Adding BedwarsRel as a plugin's dependency should work out for these scenarios.
