### ISSUE TITLE
Bug potion?

### ISSUE THREAD

**Issue by GTPATHTH** [BedwarsRel/BedwarsRel#771]
https://pastebin.com/Vs1gMwNU link

**Comment by GTPATHTH** [comment]
![2560-04-23_15 37 37](https://cloud.githubusercontent.com/assets/27913439/25312127/8bb1d15e-283b-11e7-9dd8-a85b3ba49c95.png)

**Comment by brainscript** [comment]
@GTPATHTH The item `POTION` is a water bottle and if you set `meta` to `null` you can't expect it to have any potion effects. If you want to learn how to correctly create potions, take a look at [this page](https://github.com/BedwarsRel/BedwarsRel/wiki/shop.yml#potions).
