### ISSUE TITLE
Questions:

### ISSUE THREAD

**Issue by mrblake213** [BedwarsRel/BedwarsRel#775]
1. Is it possible for the TNT Sheep to be vulnerable? Like can it be hit with a sword/hand/stick?

2. Is it possible for TNT to automatically light up when put down? Since you need to light it up with Flint and steel for it to work.

3. When the game ends, the winner spawns into his bed and doesn't leave the game or get teleported to the mainlobby. How to fix?

Thank you.

**Comment by developermatt** [comment]
Is possibile to download internal or beta releases for tests ?
 Thanks!

**Comment by sebastianbinder** [comment]
1. not possible right now.

2. not possible right now.

3. please check if there is another plugin intervening. normally this should work.
