### ISSUE TITLE
Player automatically enter game when join with BungeeCord (I don't want it)

### ISSUE THREAD

**Issue by Porama6400** [BedwarsRel/BedwarsRel#778]
If player switch server via BungeeCord, when player join Bedwars Server, the player will be put in a game
I didn't enable BungeeCord in config

Please help, I don't know how should I fix it,

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by sebastianbinder** [comment]
Any update on this?
