### ISSUE TITLE
Bungeecord geht nicht

### ISSUE THREAD

**Issue by MrLeaw** [BedwarsRel/BedwarsRel#780]
### Generelle Information
- **Version von BedwarsRel**: 1.3.4
- **Version of Spigot**: 1.8
- **Server Setup**: BungeeCord
- **Installed plugins**: nur BedwarsRel
- **shop.yml**: [shop.yml](https://pastebin.com/31gqpKzv)
- **config.yml**:  [config.yml](https://pastebin.com/5SFea9tb)
- **Errors on the Console**: Es gibt keine Errors

### Problem
Wenn ich mit BungeeCord ein Spiel erstelle und dann den Server wechseln will um die Team Spawns zu setzen aber es funktioniert nicht, da ich das Spiel noch nicht speichern kann und wenn ich dann den Server wechsel wird das SetUp abgebrochen. Muss ich ein Plugin auf den Bungeecord Server machen?

**Comment by sebastianbinder** [comment]
You need to finish the whole setup and then you'll be able to save everything.

**Comment by MrLeaw** [comment]
Aber ich kann das Setup ja nicht abschließen ohne den Server zu wechseln und wenn ich ihn wechsle wird alles verworfen. Denn zum Beispiel ist bei mir die Lobby nicht auf dem gleichen Server wie das game. oder muss ich irgendwas auf dem bungeecord Server installieren?

**Comment by sebastianbinder** [comment]
You're lobby needs to be on the same server. You're main hub can be configured in the config.
