### ISSUE TITLE
Locate_not_found for "joined"

### ISSUE THREAD

**Issue by eric2788** [BedwarsRel/BedwarsRel#781]
Version of BedwarsRel : 1.3.4 
Version of Spigot: 1.11.2
Server Setup: bungee arena
Installed plugins: 
![2017-05-03_17 03 21](https://cloud.githubusercontent.com/assets/6276840/25654108/6eb9e0ac-3022-11e7-99f8-d40a85877a3c.png)
shop.yml: same as default
config.yml: https://pastebin.com/1c9aSu4a
Errors on the Console: no
locate.yml: same as default (en_US)
Problem:
the joined message cannot be shown and display as LOCATE_NOT_FOUND
![2017-05-03_17 03 19](https://cloud.githubusercontent.com/assets/6276840/25654176/ab59220c-3022-11e7-87af-9053ee663c62.png)

**Comment by superblaubeere27** [comment]
Your problem is the language-file.
If you change the language to english it works

**Comment by eric2788** [comment]
i have changed to en_US 
but it still doesn't work

**Comment by sebastianbinder** [comment]
Fixed in latest build
