### ISSUE TITLE
Global Chat Bug

### ISSUE THREAD

**Issue by OnCraftYT** [BedwarsRel/BedwarsRel#784]
HeyHo 
Ich habe mir Bedwars reloaden Version 1.3.4 heruntergeladen und alles funktioniert bis auf den @all Chat, denn wenn man @all <Nachricht> eingibt wird alles an im Team geschrieben inklusive des @all

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by sebastianbinder** [comment]
Any update on this?
