### ISSUE TITLE
After Win: Bugs

### ISSUE THREAD

**Issue by SirLappen** [BedwarsRel/BedwarsRel#786]
Bugs after Spawn in Lobby (Spigot 1.9/ Last Version für 1.9)
Inventory is Empty!
Scoreboard on Right !
/bw leave do nothing.

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by sebastianbinder** [comment]
Any update on this?
