### ISSUE TITLE
Potion troubles(BUG) not a request/config help

### ISSUE THREAD

**Issue by ErkePannekake** [BedwarsRel/BedwarsRel#790]
I really do not understand the meaning of this bug at all it literrally makes no sense but ihave configed two pots that costs 5 iron and 2 that costs gold, but the bug itself is, it shows in shop it is costing 5 iron, 1 gold, 8 gold, 5 iron. it vdisplays it BUT it really do take my iron when i buy the pots that costs gold and if i dont have iron but i have gold i get i got not enough resources. plz fix

**Comment by sebastianbinder** [comment]
#740
