### ISSUE TITLE
[Bug?] Sign Join for Members

### ISSUE THREAD

**Issue by CoenDoesGaming** [BedwarsRel/BedwarsRel#792]
Hi, Members on my server dont go to the lobby when the click the join sign, they just get put on a team and stay where they clicked on the sign. I have no idea if this is a bug or if its a plugin doing this, if it is a bug please fix it, if it isnt do you know what plugin or plugins are doing this?

**Comment by sebastianbinder** [comment]
Hi. Just remove all your plugins except BedwarsRel and its dependencies. Then add the plugins again one by one and always check in between if it still works. That's the way how you'll find out which plugin causes the problem.
