### ISSUE TITLE
Cannot perform /bw addgame

### ISSUE THREAD

**Issue by HydroTekZ** [BedwarsRel/BedwarsRel#794]
### General Information
- **Version of BedwarsRel**: ``1.3.4``
- **Version of Spigot**: ``1.8.8``
- **Installed plugins**: ``BedwarsRel, WorldEdit, multiworld, EmptyWorldGenerator``
- **shop.yml**: [shop.yml] https://pastebin.com/EWqGKZnZ
- **config.yml**:  [config.yml] https://pastebin.com/zy4T4GLK
- **Errors on the Console**: [logfile] https://pastebin.com/TwbFJZaR

### Problem
I can't use /bw addgame MapName x
It just returns "/bw help" in white colors. I use the latest version with Spigot 1.8.8.

**Comment by sebastianbinder** [comment]
I cannot find that command in the logfile. Please provide proper data.

**Comment by sebastianbinder** [comment]
Any update on this?
