### ISSUE TITLE
Effekt Pfeil zum Shop hinzufügen!

### ISSUE THREAD

**Issue by Rowan007** [BedwarsRel/BedwarsRel#795]
Hi ich habe eine Frage.
Und zwar, wie kann man Pfeile mit einem Effekt (ID 440) zum Shop hinzufügen?
Ich habe schon einiges Ausprobiert und es geht nichts!

Falls das geht dann schreibt mir bitte wie!

Geh dies noch nicht dann wäre es nice wenn ihr das ein fügen könnet!

LG, Rowan007! :D

**Comment by sebastianbinder** [comment]
This works the same as with potions. Just add some potion meta to a tipped arrow.
