### ISSUE TITLE
It not place blocks!!!

### ISSUE THREAD

**Issue by gustavino11** [BedwarsRel/BedwarsRel#796]
On my server I put a "reloaded bedwars" plugins, I when I go into the games does not put me on the blocks, why?

**Comment by gustavino11** [comment]
is there anyone

**Comment by lucasboss45** [comment]
I don't anything anyone is gonna help you if you don't put enough details read this : 
https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue

**Comment by gustavino11** [comment]
Version of BedwarsRel: 1.3.4
Version of Spigot: spigot 1.8

**Comment by sebastianbinder** [comment]
https://github.com/BedwarsRel/BedwarsRel/wiki/FAQ#i-cannot-place-any-blocks
