### ISSUE TITLE
Physics not working + TNT Bug ?

### ISSUE THREAD

**Issue by lucasboss45** [BedwarsRel/BedwarsRel#797]
Hello I am running a single server and here are my plugins :
![image](https://user-images.githubusercontent.com/29255472/26882466-c9fe90c8-4b9a-11e7-97ee-9e48d0979fee.png)
![image](https://user-images.githubusercontent.com/29255472/26882478-d08885f2-4b9a-11e7-8b6e-3e17892fa760.png)

No errors on console showing

Shop file has not been changed

Version : Latest 1.3.4

Config not changed

I tried doing a fresh install not working

So here is my problem : 

I am currently having a problem with fire and TNT well for the fire problem players are able to put fire in the air :/
And for the TNT problem it's breaking blocks but not the bed for some weird reason for TNT i'm using a TNT Fly plugin which made TNT not breaking the beds other blocks are fine there is the plugin if you want : 
[TNTFly.zip](https://github.com/BedwarsRel/BedwarsRel/files/1058252/TNTFly.zip)

Any help would be greatly appreciated.

**Comment by lucasboss45** [comment]
Any help would be greatly appreciated.

**Comment by lucasboss45** [comment]
Can I get any kind of help please ?...

**Comment by sebastianbinder** [comment]
Actually I don't even understand your problem.

**Comment by lucasboss45** [comment]
Well let me explain this another way ;
TNT Is not able of the destroying the bed !
This issue happened when i try adding a TNTFly plugin !

**Comment by sebastianbinder** [comment]
You can enable this in your config.

**Comment by lucasboss45** [comment]
The option is enabled and as I said before this bug only started happening when I installed a TntFly :/

**Comment by sebastianbinder** [comment]
> This issue happened when i try adding a TNTFly plugin !

Please contact the developer of this plugin.
