### ISSUE TITLE
Please remove the 10-second startup delay

### ISSUE THREAD

**Issue by RoboMWM** [BedwarsRel/BedwarsRel#798]
Thanks for the warning, but I'd really not like a 10 second delay every time I start my server just because I'm compiling from source...

**Comment by sebastianbinder** [comment]
I added this, as there is no released version for 1.12 so far and I don't want anyone to keep the dev build for ages. If you are using the source, I'm sure it'll be easy for you to find the way to start your server without the delay.

**Comment by RoboMWM** [comment]
Well, yes, if I bother to maintain a fork... >_>

**Comment by sebastianbinder** [comment]
You do not even need a fork to start without a delay. Just have a proper look on the code.

**Comment by RoboMWM** [comment]
Yea, tried using github web search, apparently doesn't search any branches so yea. Thanks for the option..
