### ISSUE TITLE
I can't hit my Players and they can't hit each other

### ISSUE THREAD

**Issue by Baastey** [BedwarsRel/BedwarsRel#799]
Hello, i am using Bedwars Reloaded version 1.3.4 and I finished the setup. Everything is alright, but I and the other players can't hit themself or me. Here I show you the list of my Plugins: 
CleanroomGenerator, TTA, PerWorldChat, WorldEdit, Essentials, TuxTwoLib, BukkitSpeak, AdvancedBan, Heads, InWartung, Votifier, CustomRecipes, WorldGuard, ProtocolLib, PerWorldTabList, RewardVoting, PermissionsEx, iConomy, Ping, Vault, DailyRewards, CustomTab, MultiInv, PlotMe, Lobby, CrateReloaded, HideAndCustomPlugins, Citizens, ASkyBlock, SignColors, Spawners, ShopChest, ChatEx, PlotMe-DefaultGenerator, Multiverse-Core, BedwarsRel, PropHunt, KeepChunks, TNTRun, CommandSigns.

I am running a Single Spigot Server on the Version 1.8.8
Here you can see my config.yml: https://pastebin.com/iwJ5ybbA
Here you can see my shop.yml: https://pastebin.com/uebT7n7d

I have no errors in my console

I hope, you can help me with my Problem, because the players like Bedwars and I am looking forward to hear from you.

Gratefull
Baastey

(PS: I am not good at all in English, because I am German. I hope, you can understand my Problem)

**Comment by sebastianbinder** [comment]
I'm pretty sure, this is not being caused by BedwarsRel. Please check without any plugin except BedwarsRel and its dependencies. If this solves your problem, re-add your plugins one by one and check after each plugin. That's the way you can find out which plugin causes the problem.
