### ISSUE TITLE
MySql storage setting being ignored?

### ISSUE THREAD

**Issue by LazosPlaying** [BedwarsRel/BedwarsRel#800]
Hello, i recently started a full-network rework, and today i started on Bungeecord, one part is related to BedWars reloaded; i need a MySql storage for BedWars, but when setting the option "storage: " to "mysql" and rebooted the server, it just loaded the MySql stats.

If any other information is needed, please tell me, so i can provide it and get rid of this issues asap.

Kind regards.

**Comment by sebastianbinder** [comment]
Loading the MySQL stats when enabling MySQL seems to be right - what's the error here??

**Comment by LazosPlaying** [comment]
Sorry.. typo.

It said in console that it loaded "YAML-file" or something like that (did not copy the text)

The main issue is that (as console logs say on bootup) it is loaking YAML stats even tho the "storage" setting is set to "mysql"

If you need any more info, please tell me so. Or if you are willing to, add me on discord LazosPlaying#9695

Kind regards.

**Comment by sebastianbinder** [comment]
Ah - set storage to "database" instead of MySQL

**Comment by LazosPlaying** [comment]
okay thank you 😄 
Kind regards. (mention that in the config explanation on GitHub 😉 )

**Comment by sebastianbinder** [comment]
It is mentioned [here](https://github.com/BedwarsRel/BedwarsRel/blob/master/src/main/resources/config.yml#L445) and [here](https://github.com/BedwarsRel/BedwarsRel/wiki/Configuration)… :/

**Comment by LazosPlaying** [comment]
oh well...
I did not get this part: "# yaml or database"
Just set it to
```
# For YAML file: yaml
# For MySql database use: database
# MySql details are set in section bellow.
```
