### ISSUE TITLE
Kicks all users on join

### ISSUE THREAD

**Issue by Mikgreg** [BedwarsRel/BedwarsRel#801]
Hi,

Currently having an issue where if one particular player joins everyone on the server gets kicked off. 
This is the error message that appears in Bungee when it happens:

https://hastebin.com/otititozoj.lua

Running plugin version 1.3.4

**Comment by sebastianbinder** [comment]
This is not a BedwarsRel error. Cannot even see BedwarsRel in that stack trace.
