### ISSUE TITLE
No one can use chat and pickup items

### ISSUE THREAD

**Issue by Erry215** [BedwarsRel/BedwarsRel#803]
Hi, when I setup my arena all seems to be fine, but when I play it. For unknown reasons it is all bugged:
1. If I force it to start only myself is being teleported to the game map and it starts with only me inside
2. When we start it naturally, it seems work but, we can't use chat and we can't pickup items like iron or gold

Server is running CraftBukkit version git-Spigot-d4f98a3-cb61ac0 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

We have got the latest BedwarsRel version

Plugins (47): CoreProtect, WorldEdit, EmptyWorldGenerator, HealthBar, HackReporter, BugsyParty, SpeedBuilders, OpenInv, Essentials, ClearLag, Announcer, tpLogin, OreGenerator, TablistPrefix, WorldGuard, ProtocolLib, NoCheatPlus, SkinsRestorer, MobStacker, MinecraftItaliaRewards, Anti-Proxy, EssentialsProtect, OldPvP, EssentialsChat, EssentialsGeoIP, FreezePlus, PermissionsEx, PlaceholderHook, StaffChat, AntiBotAttack, Tablist, Vault, EssentialsSpawn, AntiCommandTab, Citizens, AuctionHouse, ASkyBlock, CommandNPC, AntiSwear, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MineResetLite, AuthMe, HolographicDisplays, LiteBans, BedwarsRel

Some console errors:
https://pastebin.com/A7e6UfB3

**Comment by sebastianbinder** [comment]
Please check again without any other plugin. If this works, please re-add those plugins and check which plugin causes this error.

**Comment by Erry215** [comment]
Ok, I found them: they're AntiCommandTab and OldPvp. Is there a future update to fix or I have to remove them?

**Comment by sebastianbinder** [comment]
That's something you need to ask the developers of those plugins. BedwarsRel isn't modifying anything.

**Comment by Erry215** [comment]
I'm really sorry for my insistence but if I remove them and I disable tab-complete from spigot.yml. It doesn't work. So can't I disable /<TAB> using this plugin?

**Comment by sebastianbinder** [comment]
Disabling tab completion should not affect anything. Disable tab completion and check again without other plugins.
