### ISSUE TITLE
Can't place items everywhere

### ISSUE THREAD

**Issue by Mikgreg** [BedwarsRel/BedwarsRel#809]
Hi! Sorry to bug.

I'm having an issue where I can only place items in tiny areas of the map, I've looked through the configs for any sort of changeable protection radius and can't find anything, also the spawn protection in server.properties is disabled.

Any kind of help for fixing this issue would be appreciated 

https://www.youtube.com/watch?v=LTnqw1bhplg

**Comment by sebastianbinder** [comment]
Check if your game region is right (in your `game.yml` - set by `bw setregion …` command).
If it is, then check again without any plugin, except BedwarsRel and its dependencies.

**Comment by sebastianbinder** [comment]
Any update on this?
