### ISSUE TITLE
WeatherChangeEvent

### ISSUE THREAD

**Issue by HydroTekZ** [BedwarsRel/BedwarsRel#813]
As I can see, you cancel WeatherChangeEvent, but you should **only** cancel if WeatherChangeEvent#toWeatherState() returns true, that means the weather is being changed to raining.

Example, this disables raining:
`@EventHandler
public void onWeatherChange(WeatherChangeEvent e) {
	if (e.toWeatherState()) e.setCancelled(true);
}`

The reason I am posting this is that the server is stuck with rain, and I cannot use /toogledownfall or /weather clear to stop the raining since your plugins just cancels it. To fix this I have to stop the server and remove the plugin and then turn off raining.

**Comment by sebastianbinder** [comment]
But maybe there are maps, where it should rain… Just remove the jar-file of BedwarsRel from your plugins for a short moment, then change the weather and re-add the plugin.

**Comment by HydroTekZ** [comment]
Well, that's true... :P
