### ISSUE TITLE
BedWarsRel.jar überschreibt sich?

### ISSUE THREAD

**Issue by DieLaugenBrezel** [BedwarsRel/BedwarsRel#814]
Jedes mal wenn ich den Server neustarte oder reloade wird die BedWarsRel.jar 1KB groß und wird in Minecraft bei /pl nicht mehr angezeigt. Es werden auch alle Spiele gestoppt 👎  Das nerft voll wenn ich jedes mal die JAR-Datei neu reinziehen muss

PS: Es ist egal ob Spigot oder Bungeecord
BedWarsRel.jar-Version: 1.3.4

**Comment by DieLaugenBrezel** [comment]
UPDATE: habe auf 1.3.5 geupdatet, jetzt gehts 👍

**Comment by sebastianbinder** [comment]
Das ist leider dieser blöde Auto-Updater - der ist irgendwie kaputt
