### ISSUE TITLE
SpectatorMode

### ISSUE THREAD

**Issue by MPK1** [BedwarsRel/BedwarsRel#817]
Hi there,

I'm missing a SpectatorMode in your plugin. Currently in BungeeMode, it is possible to join to servers where a game is running. Is it intended to be like that? Because players can run around in the game-lobby and break blocks and so on... It would be great if EITHER players were kicked when joining the game, if it is in bungee mode OR players joining a running game would be teleported to the map-world and the gamemode is set to spectatormode.

Thank you for a short answer if this is possible...

**Comment by sebastianbinder** [comment]
There is a proper working spectator mode. Just have a look on the config (obviously you have never done so) and check if any other plugin on your server interferes here.
