### ISSUE TITLE
Saving record destroys server

### ISSUE THREAD

**Issue by HydroTekZ** [BedwarsRel/BedwarsRel#818]
A user of my server said the server stopped working after a new record was set.

Server logs: https://pastebin.com/h0yPfDY4
Error message: https://pastebin.com/LtSx84mK

I use the last version of Spigot 1.8.8 (r3) and BedwarsRel 1.3.5.

Btw, this has started happening often on many of my Bedwars servers. Pretty annoying, and my server seems pretty unprofessional when that happens. 

PS: I won't update to 1.12, it is a matter of fact that I downgraded to 1.8 a couple of weeks ago. Bedwars has better gameplay on 1.8.

**Comment by sebastianbinder** [comment]
-> #816
