### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by viamixl** [BedwarsRel/BedwarsRel#819]
# **German**
Ich gibt es einen Fehler gefunden haben, und das ist, dass, wenn Sie Bettwaren rel in Multi-Arena nutzen / ohne Bungee es so versauen, wenn Sie viele Arena haben. mein Server verfügt über 14 Veranstaltungsorten und den Scheiß oft bis Sie das Problem beheben können

# **English**
It's a bug I've found and it's that if you use bedwars rel in the multi arena / without bungee it bugs up if you have many arena. My server has 14 arenas and it often bugs you can fix it

**Comment by sebastianbinder** [comment]
I have no idea what you are talking about. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by sebastianbinder** [comment]
any update on this?
