### ISSUE TITLE
Hey i edited my config and the shops top collum does not show up ?

### ISSUE THREAD

**Issue by SgtDirk** [BedwarsRel/BedwarsRel#820]
--- 
armor: ~
item: DIAMOND_CHESTPLATE
lore: 
  - "Protect yourself with armor! Click here."
name: Armour
offers: ~
order: 10
permission: bw.base
shop: ~  
 - price:
      - type: IRON_INGOT
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1 
 - price:
      - type: IRON_INGOT
      reward:
      - type: LEATHER_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
      reward:
      - type: LEATHER_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
      reward:
      - type: LEATHER_BOOTS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1

    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: CHAINMAIL_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: IRON_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: IRON_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: IRON_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: DIAMOND
        amount: 5
      reward:
      - type: IRON_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1

    - price:
      - type: EMERALD
        amount: 10
       reward:
      - type: IRON_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "Magnet-Shoes"
          lore:
          - "Wear those shoes and have a 75%"
          - "chance of getting no knockback!"
    - price:
      - type: EMERALD
        amount: 10
      reward:
      - type: DIAMOND_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: EMERALD
        amount: 10
      reward:
      - type: DIAMOND_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: EMERALD
        amount: 10
      reward:
      - type: DIAMOND_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: EMERALD
        amount: 10
      reward:
      - type: DIAMOND_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1

**Comment by sebastianbinder** [comment]
Please do proper markdown formatting and have a look on the wiki entry "How to write an issue".

**Comment by sebastianbinder** [comment]
Still not a properly readable yml config. Will be closed until proper information is provided.
