### ISSUE TITLE
Cant Build

### ISSUE THREAD

**Issue by gravehq** [BedwarsRel/BedwarsRel#821]
Hello, just have a Problem with Building the Plugin

18:21:13 INFO]: Set PluginClassLoader as parallel capable
[18:21:13 ERROR]: Could not load 'plugins\BedwarsRel-Common-1.3.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/bugsnag/callbacks/Callback
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)

I used Maven Clean Install
any Idea what I can do?

**Comment by sebastianbinder** [comment]
Because "Common" is not the plugin. Use the "Plugin" artifact.

**Comment by gravehq** [comment]
Okay, but still https://hastebin.com/cehahanini.sql
