### ISSUE TITLE
Colored Bocks for every team

### ISSUE THREAD

**Issue by GhostsDE** [BedwarsRel/BedwarsRel#823]
As First sry for my Bad english.
I have an idea to add Colored Blocks. I See this on another Server like minesucht.net. But mal questions is to add Blocks for everybody Team in the Team Color. I Thing with this Feature you would bring a lot of Color in this Game, instead of Boring Same blocks.
It is just an Idea. I Love your plugin and Want to help to make ist better.
Ghost.

**Comment by sebastianbinder** [comment]
Colored blocks are already available.
