### ISSUE TITLE
Wooden pressure plate

### ISSUE THREAD

**Issue by bwzzwt** [BedwarsRel/BedwarsRel#825]
Buy wooden pressure plate An error occurred:https://pastebin.com/hw4BmvpW
shop:
    - reward:
      - type: WOOD_PLATE
      price:
      - type: GOLD_INGOT
        amount: 2

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by bwzzwt** [comment]
@sebastianbinder Shop and Error Console already provided ,what else do you need?      i think that is enough.

**Comment by sebastianbinder** [comment]
There is no proper shop file attached. you did not mention any server version and so on… Just read that wiki entry and provide the information requested.

**Comment by bwzzwt** [comment]
@sebastianbinder delete Shop file this error be rectified, What is the meaning of providing information?

**Comment by sebastianbinder** [comment]
just give me everything requested in that wiki entry.

**Comment by bwzzwt** [comment]
@sebastianbinder Before I provide other information, can not you judge the cause of the error based on the shop and console error messages I have provided?
https://imgur.com/a/Z6On4

**Comment by sebastianbinder** [comment]
I maybe could. But support for a free and open source plugin is still a voluntary thing. And as things are much easier with a complete set of information and I don't have too much freetime I cannot handle such imprecise requests.
Issue will be closed until information needed has been provided.
