### ISSUE TITLE
Item Frame Glitch

### ISSUE THREAD

**Issue by whitelily36** [BedwarsRel/BedwarsRel#828]
### General Information
- **Version of BedwarsRel**: ``1.3.4 and above``
- **Version of Spigot**: ``1.11.2 and 1.12``
- **Server Setup**: ``Multiverse server`
- **Installed plugins**: ``craftconomy3, votifier, playerheads, dynmap, worldboard, protocollib, idisguise, permissionex, xinventories, multiverse-core, essentials, furniturelib, dicefurniture, worldedit, acidisland, askyblock, survivalgames, paintball, protectionlib, craftbook, reportrts, lwc, logblock, slimefun, worldguard, LWC, MyPet (and more...)``
- **shop.yml**: [shop.yml](LINK-TO-PASTEBIN)
- **config.yml**:  [config.yml](LINK-TO-PASTEBIN)
- **Errors on the Console**: [logfile](LINK-TO-PASTEBIN) No errors appearing

### Problem

We were first alerted to a problem with bedwars when our MyPet pets became invisible after updating our server to 1.12.  The MyPet author helped us fix it and told us the issue was with Bedwars, but he put a fix into his plugin for us (see here - https://github.com/xXKeyleXx/MyPet/commit/2c478d568f49f821edfc7ae75fd5c805f79b8ac6).  Then not long ago we found that (in any world), if you right click with a block in your hand, on the block an item frame is sitting on, then it duplicates the block you are holding.  It could duplicate any block, even shulker boxes.  When I removed bedwars from the server, this glitch went away.  I do hope you can look into this because my community will be upset to lose bedwars, they really enjoy it.  However we cannot leave this glitch as it is a gamebreaker.

**Comment by sebastianbinder** [comment]
Cannot reproduce. Maybe I simply don't understand the procedure. Please provide a little video showing the steps to reproduce.

**Comment by whitelily36** [comment]
Also an image attached showing our plugins

**Comment by sebastianbinder** [comment]
Cannot see any video.

**Comment by whitelily36** [comment]
I sent a zipped file called Duplicate Glitch - just unzip it.

**Comment by sebastianbinder** [comment]
Cannot see any ZIP on this thread.

**Comment by whitelily36** [comment]
[Duplicate Glitch.zip](https://github.com/BedwarsRel/BedwarsRel/files/1150313/Duplicate.Glitch.zip)

**Comment by sebastianbinder** [comment]
Thank you. I'll look into this as soon as semester at uni has ended in 2-3 weeks.

**Comment by whitelily36** [comment]
Any news on this?  Even after updating to 1.12.1, this bug still exists, so we cannot use the plugin.

**Comment by whitelily36** [comment]
Could I ask if this has been looked at yet?

**Comment by sebastianbinder** [comment]
I just had a look on this and it seems that this is not an issue directly being caused by BedwarsRel. BedwarsRel checks if a block is being placed on an item frame which is part of the map and therefor must not be destroyed. So it simply drops that block again. But this takes almost takes 5 seconds. In your video the blocks are dropping really fast. So there must be another plugin which interferes here. I cannot remove the corresponding part of BedwarsRel's code. So it simply is a compatibility issue which cannot be solved.
