### ISSUE TITLE
Perms problem

### ISSUE THREAD

**Issue by zwibblTV** [BedwarsRel/BedwarsRel#829]
After update to 1.3.6 i don´t have permissions to do anything. I am OP and have the bw.* permission.
Please help, the plugin is so nice!

**Comment by sebastianbinder** [comment]
1.3.6 only changed this: https://github.com/BedwarsRel/BedwarsRel/commit/6fd6c61895e2dbbc4f4a6782d3815672380e379f#diff-453941e5088c679856ba6cab60b5b9aa
nothing about permissions.
so please provide proper information according to https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue

**Comment by zwibblTV** [comment]
### General Information
- **Version of BedwarsRel**: ``1.3.6``
- **Version of Spigot**: ``1.12``
- **Server Setup**: ``single-server``
- **Installed plugins**: ``AntiBuild,BedwarsRel,ChairStairs,ColorCube,DicoBeacon,dynmap,Essentials,-AntiBuild,-Chat,-Protect,-Spaw,ImageMaps,LogBlock,MarriageMaster,MCJukebox,MineMaze,Multiverse-Core,-Inventories,-NetherPortals,-Portals,OITC,OpenInv,PermissionsEx,SignURL,TPC,Turnstile,TWM,Vault,WeatherVote,WGTimeFlags,WorldEdit,worldguard``
- **shop.yml**: https://pastebin.com/W0virZ9Q
- **config.yml**:  https://pastebin.com/KY9VWDdw
- **Errors on the Console**: there where nothing

### Problem
Our problem is in the permissions. If we try to enter any command we just get that "you don't have permission" even if we are OP or have the bw.* permission node. This is new since the newest update came out. We already tried to reinstall the whole plugin but it didnt work. It worked in MC 1.12 with BedwarsRel-1.3.5 perfect!

**Comment by sebastianbinder** [comment]
As I cannot reproduce this, have you tried after removing any other plugin except BedwarsRel and its dependencies to make sure this isn't caused by any other plugin?

**Comment by sebastianbinder** [comment]
Any update on this?

**Comment by zwibblTV** [comment]
Well, it works now brilliant!
We don´t know why, but after reinstalling all worked quite nice.
Thanks for answering!
Little question: Could you may implement an spy like a bat or something like this? Would be nice! ^^
