### ISSUE TITLE
I found a bugg with the Viligers

### ISSUE THREAD

**Issue by RengoCraft** [BedwarsRel/BedwarsRel#831]
I found a bugg with the Viligers sometimes when i fall down and spawn to my island in a bw game i cant see my Viliger but my Friend can see it and it's sometimes the same with my Friends

**Comment by sebastianbinder** [comment]
Remove any plugin except BedwarsRel and its dependencies. If it works like that, re-add your plugins one by one to see which plugin causes the error. I'm a 100% sure, this is not being caused by BedwarsRel.
