### ISSUE TITLE
Sign Promblem (I Think)

### ISSUE THREAD

**Issue by Kyry231** [BedwarsRel/BedwarsRel#832]
So I have been through the config about 20 times and i cannot find the sign configuration for the title of the sign. I have found at the bottom of the config the sign layout but it says it goes to the title which is around the top. I have switched the title of the sign but when i reload it, it still says BEDWARS and it has really bugged me (haha get it?) but i really hope you can fix this because this is an issue if you want to rename bedwars to something else.

**Comment by sebastianbinder** [comment]
Hi. I don't get the issue out of this. Please try to describe it in other words or add examples.

**Comment by Kyry231** [comment]
The sign will not change the top part to what i have named it to. It will just stay Bedwars and it is just a little annoying. But here is an example
                                 
[Bedwars]
    Map
  Players
Waiting...

That is the sign layout and as you can see at the top that is what im trying to change to Crafting Wars. If you could find a way to fix this or tell me what im doing wrong that would be great. I found this issue because in the config it looks like you can change the sign layout but that is all i wanted to change so ya thanks for taking time out of your day to help me

**Comment by sebastianbinder** [comment]
Just change
```yml
sign:
  first-line: $title$
```
to e.g.
```yml
sign:
  first-line: "Crafting Wars"
```
in your `config.yml`
