### ISSUE TITLE
Console Error when adding new player to yaml statistics

### ISSUE THREAD

**Issue by Jellypowered** [BedwarsRel/BedwarsRel#833]
### General Information
- **Version of BedwarsRel**: 1.36
- **Version of Spigot**: latest
- **Server Setup**: single
- **Installed plugins**: bedwars 1.36
- **shop.yml**: [shop.yml] factory setup
- **config.yml**:  [config.yml] https://pastebin.com/58JsLKYQ
- **Errors on the Console**: [logfile] https://pastebin.com/ubXWAZvc

### Problem
Not plugin breaking, just noticed this error. 

When a player that hasn't played bedwars before joins a game, this error is thrown on the console because they aren't stored in the yaml storage for the statistics. (everything still works just thought you should know)

**Comment by sebastianbinder** [comment]
Thank you. I'll look into this as soon as semester at uni has ended in 2-3 weeks.
