### ISSUE TITLE
Is master branch considered a development version?

### ISSUE THREAD

**Issue by RoboMWM** [BedwarsRel/BedwarsRel#835]
So, is compiling from master considered a development build?

Either way, wish you would at least change the system property instead of just outright copying spigot's code. Not to mention that code was for outdated versions - this one just indiscriminately freezes all versions.

**Comment by sebastianbinder** [comment]
`if (this.getDescription().getVersion().contains("-SNAPSHOT")`

So this means it depends on the profile being used when compiling (https://github.com/BedwarsRel/BedwarsRel/blob/master/pom.xml#L53)
