### ISSUE TITLE
Items do not spawn.

### ISSUE THREAD

**Issue by montlikadani** [BedwarsRel/BedwarsRel#839]
**BedWarsRel version:** 1.3.6
**Spigot version:** spigot-1.8.8-R0.1-SNAPSHOT
**Server setup:** Single Server
**Installed plugins:**
BedWarsRel
ChatControl
Essentials
EssentialsChat
EssentialsGroupManager
LaggRemover
Lobby
Multiverse-Core
NoCheatPlus
PerWorldChat
SpawnJoin
sTablist
Vault
Worldedit
Worldguard
**config.yml:** https://pastebin.com/PYrtqyLE
**shop.yml:** https://pastebin.com/vzrv4LsE
**Errors on the Console:** no errors on console
**Problem:**
So. I did everything I could but did not spawn items.
Yeah and during the game, time is not reckoned. And at the end of the game, he does not recall that when he is teleported back to the lobby slot he is set up in just another world.

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.
