### ISSUE TITLE
Y

### ISSUE THREAD

**Issue by Waffles2112** [BedwarsRel/BedwarsRel#840]
its the best free bedwars plugin in my opinion
theres just a slight problem when you join an arena located in a different world, it gives you the items you had in the world u were teleported from along with the bedwars lobby items

plz fix

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.
