### ISSUE TITLE
Bedwars Rel plugin. Wie verbinde ich dei Server das man über die Schilder Joinen kann

### ISSUE THREAD

**Issue by Chickakaddle** [BedwarsRel/BedwarsRel#841]
Hi,
ich habe eine frage und zwar, habe ich einen BungeeCord server eröffnet und er befindet sich momentan in der PreAlpha. Ich möchte gerne das Bedwars-Rel einstellen. habe in der Confiq Bungecord auf "true" gesetzt und die ganzen teams, spawner und die Wartelobby eingestellt. nun möchte ich das schild auf dem Lobbyserver erstellen. Wird aber nichts angezeigt. Habe bisher auch kein Video gefunden, wie man das einstellen kann.
Könnten sie mir das eventull erklären, wie das geht ?

Vielen Dank im Vorraus.

Mit freundlichen Grüßen

Chickakaddle

**Comment by sebastianbinder** [comment]
You need to use another plugin like Teleport Signs which will read your server's motd which is being set by BedwarsRel.
