### ISSUE TITLE
PlayerPickupItemEvent WARN

### ISSUE THREAD

**Issue by andris155** [BedwarsRel/BedwarsRel#843]
`[00:24:49] [Server thread/WARN]: [BedwarsRel] "BedwarsRel v1.3.6" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void io.github.bedwarsrel.listener.PlayerListener.onPickup(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [The BedwarsRel-Team | www.github.com/orgs/BedwarsRel/people].`

**Comment by sebastianbinder** [comment]
@andris155 thank you.
Could you please check on following dev build (https://4103-32877020-gh.circle-artifacts.com/0/artifacts/BedwarsRel-1.3.7-SNAPSHOT.jar) if the warning has gone there? thank you!
