### ISSUE TITLE
Cant place block!!!! plz help

### ISSUE THREAD

**Issue by OddOcelotYT** [BedwarsRel/BedwarsRel#844]
I have created bedwars map adn got everything set up but when we start playing the blocks we buy wont place can someone please tell me how to fix this

**Comment by sebastianbinder** [comment]
Pretty sure this will help you: https://github.com/BedwarsRel/BedwarsRel/wiki/FAQ#i-cannot-place-any-blocks

**Comment by OddOcelotYT** [comment]
thank you i will try that out

**Comment by OddOcelotYT** [comment]
i have tryed that and it still wont work i am using aternos server hosting
