### ISSUE TITLE
Public Chat

### ISSUE THREAD

**Issue by Tr0nDraws** [BedwarsRel/BedwarsRel#848]
When Im In Game I Cant Talk To Pepole In Different Teams, Is There A Way To Enable It?

**Comment by sebastianbinder** [comment]
Just have a proper look at the config. It’s not that hard to find out… :/

**Comment by Tr0nDraws** [comment]
i tried to do that
lobby-chatformat: '$player$: $msg$'
ingame-chatformat-all: '[$all$] <$team$>$player$: $msg$'
ingame-chatformat: '<$team$>$player$: $msg$'

**Comment by Tr0nDraws** [comment]
i deleted some i replaced others. nothing worked

**Comment by Tr0nDraws** [comment]
i couldnt figure it out, please help!
