### ISSUE TITLE
I Took A Look

### ISSUE THREAD

**Issue by Tr0nDraws** [BedwarsRel/BedwarsRel#849]
lobby-chatformat: '$player$: $msg$'
ingame-chatformat-all: '[$all$] <$team$>$player$: $msg$'
ingame-chatformat: '<$team$>$player$: $msg$'

**Comment by Tr0nDraws** [comment]
Still Have No Idea! PLEASE HELP ME

**Comment by Tr0nDraws** [comment]
How Do I Make All Teams Be Able To Talk To Eachother

**Comment by sebastianbinder** [comment]
Interesting. Cause my config file has settings like chat-to-all-prefix and separate-game-chat …

**Comment by Tr0nDraws** [comment]
couldnt find it sorry


On Thu, Aug 17, 2017 at 11:48 AM, Sebastian Binder <notifications@github.com

**Comment by Tr0nDraws** [comment]
chat-to-all-prefix:
- '@'
- '@a'
- '@all'
seperate-game-chat: false

that doesnt work.

**Comment by Tr0nDraws** [comment]
what do i do to fix dis
