### ISSUE TITLE
Permenant Full Armour Sets

### ISSUE THREAD

**Issue by Tr0nDraws** [BedwarsRel/BedwarsRel#850]
is there a way to turn this
    - price:
      - type: IRON_INGOT
      amount: 8
      reward:
      - type: LEATHER_HELMET
into a full set of armour that doesnt get destroyed when you die, the only way to remove it is for the game to end or for a better set of armour to be bought

**Comment by sebastianbinder** [comment]
There are plenty of feature requests like that. Might be implemented in the future.
