### ISSUE TITLE
Fireworks

### ISSUE THREAD

**Issue by Tr0nDraws** [BedwarsRel/BedwarsRel#852]
I Was Not Able To Add Fireworks To The Shop And I Tried A Few Things, I Tried 
FIREWORKS
FIREWORK_ROCKET
FIREWORK_ROCKETS
and the id

i could not get it to work, any help?

    - price:
      - type: EMERALD
      reward:
      - type: FIREWORKS

**Comment by flixoflax** [comment]
Hello! Its think I have The answer for your Problem... Try FIREWORK you Can find all spigot Materials at: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by Smokescrean** [comment]
Hey so have u found solution? I have the same problem

**Comment by Tr0nDraws** [comment]
omg this was like 3 years ago man, I never found out how but I empathize
with you. sorry and good luck

**Comment by Smokescrean** [comment]
Thanks for gl :) I solverd this problem adding gunpowder, paper and allowed crafting for players
