### ISSUE TITLE
Having this error

### ISSUE THREAD

**Issue by FakeFlake** [BedwarsRel/BedwarsRel#853]
`19:10:55 | Could not pass event PlayerJoinEvent to BedwarsRel v1.3.6
19:10:55 | org.bukkit.event.EventException: null
19:10:55 | 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:171) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:63) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:202) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:937) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1168]
19:10:55 | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
19:10:55 | Caused by: java.lang.NullPointerException
19:10:55 | 	at io.github.bedwarsrel.statistics.PlayerStatisticManager.loadYamlStatistic(PlayerStatisticManager.java:241) ~[?:?]
19:10:55 | 	at io.github.bedwarsrel.statistics.PlayerStatisticManager.loadStatistic(PlayerStatisticManager.java:225) ~[?:?]
19:10:55 | 	at io.github.bedwarsrel.listener.PlayerListener.onJoin(PlayerListener.java:671) ~[?:?]
19:10:55 | 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor419.execute(Unknown Source) ~[?:?]
19:10:55 | 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1168]
19:10:55 | 	... 15 more`

And then the player can't move. I have to delete their player file. Didn't have this issue for first week, then recently started to get it.

**Comment by Behoston** [comment]
+1

**Comment by sebastianbinder** [comment]
Already fixed in #846 - and I’m a 100% sure this issue does not cause any player movement issues.

**Comment by Flame3050** [comment]
So how do I fix it
