### ISSUE TITLE
Voten für Gold

### ISSUE THREAD

**Issue by rexwin2001** [BedwarsRel/BedwarsRel#855]
Hi, ich habe noch eine Feature Idee. Könntet ihr in BedBedwa Reloade es so machen das man für Gold voten kann. Das wäre ein mega Game Feature. Wäre Hammer wenn es raus kämme.

MLG Twitchezocker

**Comment by flixoflax** [comment]
Jap das finde ich auch ein Hammer Feature!!!

**Comment by sebastianbinder** [comment]
We won't implement this, as this is not a feature of the Bedwars gameplay. Any developer can code this for your server within a couple of minutes.
