### ISSUE TITLE
Setting for distance between player and rescue platform

### ISSUE THREAD

**Issue by flixoflax** [BedwarsRel/BedwarsRel#857]
Liebes BedwarsRel-Team, 

Als erstes schätze ich eure Arbeit sehr! Allerdings ist mir etwas aufgefallen und zwar wenn ich meine Rettungsplattform öffne setzt sie sich genau einen Block unter mir das bedeutet das man keinen chance mehr hat einen MLG durchzuführen... d.h. Ich wünsche mir eine Einstellmöglichkeit um den Abstand zwischen Player und Plattform in Blöcken einzustellen! 

LG Flixoflax

**Comment by sebastianbinder** [comment]
Added in https://github.com/BedwarsRel/BedwarsRel/commit/b22bf6e2ec5973b95c6d98c2f55e1b6ba8408fd0

Available in latest dev-build (https://4136-32877020-gh.circle-artifacts.com/0/artifacts/BedwarsRel-1.3.7-SNAPSHOT.jar).

**Comment by flixoflax** [comment]
Hey!! Wann ist das offizielle Release?Am 06.10.2017 07:44 schrieb Sebastian Binder <notifications@github.com>:Added in b22bf6e
Available in latest dev-build (https://4136-32877020-gh.circle-artifacts.com/0/artifacts/BedwarsRel-1.3.7-SNAPSHOT.jar).
