### ISSUE TITLE
BedwarsRel - Spectatormode

### ISSUE THREAD

**Issue by flixoflax** [BedwarsRel/BedwarsRel#858]
Liebes BedwarsRel-Team,
Für das nächste Update wünsche ich mir einen verbesserten Spectatormodus ähnlich wie bei GommeHd.net und rewinside.tv d.h das der Gamemode Survival sein sollte und jeder Spectator gevanished ist und fliegen kann. Danke!

**Comment by sebastianbinder** [comment]
There is Gamemode 3 as official spectator mode in Minecraft. So there is no reason to add a custom spectator mode.

**Comment by flixoflax** [comment]
True. But you are not able to see the Hotbar

**Comment by sebastianbinder** [comment]
There is no need to see the hotbar. You can always access your inventory via your keyboard and even use the spectator items being given to you by BedwarsRel.
