### ISSUE TITLE
Armor / Auto Equip

### ISSUE THREAD

**Issue by Tr0nDraws** [BedwarsRel/BedwarsRel#859]
is there a way to get multiple items in 1 shop buy, like in shop.yml can you make
    - price:
      - type: IRON_INGOT
        amount: 16
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
but it also give another item, and can you make it so it auto equips?

**Comment by flixoflax** [comment]
No this is not possible. If you want to have the SAME Item for example twice you can add the amount in the Shop.yml like this:

amount: 2

But its not possible to give multiple DIFFERENT items.

**Comment by Tr0nDraws** [comment]
is it possible to make it so it auto equips tho?

**Comment by flixoflax** [comment]
You can Do this by making your own script with the plugin Skript you can find it on bukkit.

**Comment by sebastianbinder** [comment]
In BedwarsRel there won't be any kit-like features.
