### ISSUE TITLE
Confused on Bungeecord

### ISSUE THREAD

**Issue by HellaMixel** [BedwarsRel/BedwarsRel#865]
This is sort of an issue, but not a total issue. I am confused on how the bungeecord thing works. So I have a hub, and I have a BedWars server. I don't understand how you go from Bedwars clicking a sign to another server where the Arena would be? I think I have the entire concept of this wrong, correct me please. Does it go Hub to BedWars to Clicking a sign to Joining a lobby where you pick teams in a separate server, then you join the Arena in the same server with multiverse? I am really confused.

**Comment by flixoflax** [comment]
Hello, 
Install this plugin https://www.spigotmc.org/resources/teleport-signs.37446/
If you have done it you can setup a BungeeTeleportSign to your Bedwars-Server now enable bungeecord - mode in the config of your Bedwars-Server - - > now you can join the game by clicking on the bungeesign.
