### ISSUE TITLE
Shop is not working

### ISSUE THREAD

**Issue by BlueYetiGaming** [BedwarsRel/BedwarsRel#867]
After downloading the plugin and configuring everything that is needed for the game to work, my only problem is the shop. I can use the default shop and everything works fine, however I wanted to customize it so I did following the format of the default code used in the Shop.yml. This is my newly configured Shop.yml: https://pastebin.com/7UQEV6kf. Anyways the problem is when I start a bedwars game and join, once I am in and click on the shop two items show one is a snow ball that says "use default shop" and then there is a lava bucket that says "shift click for full stack". I am guessing I messed something up in the Shop.yml but I don't know what and I even copy and pasted the code from shop.yml into http://www.yamllint.com/ to verify that the code was formatted correctly. Any help on fixing my issue would be greatly appreciated.

**Comment by flixoflax** [comment]
Shop is configured wrong

**Comment by sebastianbinder** [comment]
If you are not able to completely modify the shop without producing errors, then start with the default shop.yml and change it item per item. So you'll find out whats wrong there. If you have a specific offer in your shop which does not work, then I can have I look on it. I don't have enough time to check your whole shop.yml
