### ISSUE TITLE
Spectator Problems

### ISSUE THREAD

**Issue by Ben08091011** [BedwarsRel/BedwarsRel#872]

**Comment by Ben08091011** [comment]
(addition) I know this doesnt have to do with spectator, but one more issue. How do i make my own special items? I want to add the silver fish thing like hypixel. Thank you!!!

**Comment by sebastianbinder** [comment]
A player spectating is being set to the Spectator Gamemode which has no hotbar (that's simply how Minecraft works).
If there is something wrong with the game mode after a game has ended, please some more details. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let me know as much as possible about your setup.

Regarding Special Items: You can simply ask your developer to check on different events. There is no need to hook into BedwarsRel for adding some more special items. Just add the material of this item to the shop.

**Comment by Ben08091011** [comment]
Regarding spectator: I understand, but can it be set up for spectators of the game to simply be in gamemode 0, and regarding the Special items: I am my own developer, and want to try to create my own special itens. Please help

**Comment by Ben08091011** [comment]
ALSO after the game ends, if ur a spectator u fall into the void
