### ISSUE TITLE
[Feature]Delay when respawning and no respawn prompt

### ISSUE THREAD

**Issue by xicciodj** [BedwarsRel/BedwarsRel#878]
Hi!
I'm using Bedwars-Rel on my Spigot server, but I'm not able to config two features (maybe these aren't present?)

I want to enable a 5 seconds delay when a player respawns after death, instant kill when a player falls into the void and I want to remove the Respawn screen.

Sooo.... How can I do this? Should I use external plugins or does Bedwars-Rel support these things? Thanks in advance...

P.S. Sorry for the (maybe) bad English.

**Comment by sebastianbinder** [comment]
Already configurable -> https://github.com/BedwarsRel/BedwarsRel/blob/master/common/src/main/resources/config.yml

**Comment by xicciodj** [comment]
I can't see configurations about respawning delay.

**Comment by elmahdiDev** [comment]
its not
