### ISSUE TITLE
PVP

### ISSUE THREAD

**Issue by RoboCreeper606** [BedwarsRel/BedwarsRel#883]
BedwarsRel Version: Latest
Spigot Version: 1.12.2
Server: Normal?
Plugins: Cleanroomgenerator, WorldEdit, BuycraftX, Vault, Multiverse-Core, Protocol Lib, Citizens, Holographic Displays, BedwarsRel and Citizens CMD.
Shop: ### SHOP ###
### NOT ALLOWED CATEGORY MATERIAL: SLIME_BALL, SNOW_BALL, BUCKET, LAVA_BUCKET
shop:
  armor:
    item: DIAMOND_CHESTPLATE
    name: "Armour"
    order: 10
    permission: bw.base
    lore:
    - "Protect yourself with armor! Click here."

    offers:
    - price:
      - type: DIAMOND
        amount: 2
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 4
      reward:
      - type: LEATHER_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 3
      reward:
      - type: LEATHER_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: DIAMOND
        amount: 2
      reward:
      - type: LEATHER_BOOTS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 2

  swords:
    item: DIAMOND_SWORD
    name: "Swords"
    order: 20
    permission: bw.base
    lore:
    - "Click here to get sword for attacking your enemies"
    offers:
    - price:
      - type: DIAMOND
        amount: 8
      reward:
      - type: STICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1

  bows:
    item: BLAZE_ROD
    name: "Specials"
    order: 30
    permission: bw.base
    lore:
    - "Click here to get sword for attacking your enemies"
    offers:
    - price:
      - type: DIAMOND
        amount: 12
      reward:
      - type: STICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 99
    - price:
      - type: DIAMOND
        amount: 6
      reward:
      - type: ENDER_PEARL
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
schema-version: 1
Config: # ###############################
# ####### BEDWARS CONFIG ########
# ##### CREATED BY YANNICI ######
# ###############################
# ###### EXPLANATION ABOUT ######
# ##### EVERY CONFIGURATION #####
# ### YOU CAN FIND ON GITHUB ####
# ############ WIKI #############
# ###############################
# 
# # TYPE HELP # #
# int: number (not decimal)
# string: a normal text (in most cases you can use colorcodes with a beginning §)
# boolean: true or false (IMPORTANT: true OR false ONLY)
# list<?>: a list of type ? (? is the type of the list items)
# byte: a int but limited between -128 ... 127
# short: a int but limited between -32768 ... 32767
# char: one character

chat-prefix: '&7[&bBedWars&7]&f'
plugin-metrics: true
send-error-data: true
global-messages: true
global-autobalance: false
global-chat-after-end: true
gamelength: 60
allow-crafting: false
overwrite-names: false
lobby-gamemode: 0
holographic-stats:
  show-prefix: false
  name-color: '&7'
  value-color: '&e'
  head-line: Your &eBEDWARS&f stats
teamname-on-tab: false
teamname-in-chat: false
hearts-on-death: true
die-on-void: false
spawn-ressources-in-chest: true
lobbytime: 60
lobby-chatformat: '$player$: $msg$'
ingame-chatformat-all: '[$all$] <$team$>$player$: $msg$'
ingame-chatformat: '<$team$>$player$: $msg$'
game-block: BED_BLOCK
store-game-records: true
store-game-records-holder: true
bed-sound: ENTITY_ENDERDRAGON_GROWL
player-drops: true
keep-inventory-on-death: false
place-in-liquid: true
breakable-blocks:
  use-as-blacklist: false
  list:
  - none
jointeam-entity:
  show-name: true
lobby-scoreboard:
  enabled: true
  title: '&eBEDWARS'
  content:
  - ' '
  - '&fMap: &2$regionname$'
  - '&fPlayers: &2$players$&f/&2$maxplayers$'
  - ' '
  - '&fWaiting ...'
  - ' '
scoreboard:
  format-bed-destroyed: '&c$status$ $team$'
  format-bed-alive: '&a$status$ $team$'
  format-title: '&e$region$&f - $time$'
titles:
  win:
    enabled: true
    title-fade-in: 1.5
    title-stay: 5.0
    title-fade-out: 2.0
    subtitle-fade-in: 1.5
    subtitle-stay: 5.0
    subtitle-fade-out: 2.0
  map:
    enabled: false
    title-fade-in: 1.5
    title-stay: 2.0
    title-fade-out: 1.5
    subtitle-fade-in: 1.5
    subtitle-stay: 2.0
    subtitle-fade-out: 1.5
  countdown:
    enabled: true
    format: '&3{countdown}'
explodes:
  destroy-worldblocks: false
  destroy-beds: false
  drop-blocking: false
friendlyfire: false
friendlybreak: true
gameoverdelay: 10
use-internal-shop: true
save-inventory: true
show-team-in-actionbar: true
chat-to-all-prefix:
- '@'
- '@a'
- '@all'
seperate-game-chat: true
seperate-spectator-chat: false
statistics:
  enabled: false
  show-on-game-end: true
  storage: yaml
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
  player-leave-kills: false
database:
  host: localhost
  port: 3306
  db: database
  user: root
  password: secret
  table-prefix: bw_
spectation-enabled: false
respawn-protection: 0
allowed-commands:
- /help
endgame:
  mainlobby-enabled: false
  all-players-to-mainlobby: false
bungeecord:
  enabled: false
  hubserver: hub
  endgame-in-lobby: true
  full-restart: true
  spigot-restart: true
  motds:
    lobby: |
      $regionname$
      &7[&b$currentplayers$&7/&b$maxplayers$&7]
    running: |
      $regionname$
      &7[&b$currentplayers$&7/&b$maxplayers$&7]
    stopped: |
      $regionname$
      &c[Stopped]
    full: |
      $regionname$
      &7[&b$currentplayers$&7/&b$maxplayers$&7]
locale: en_US
resource:
  bronze:
    item:
    - type: CLAY_BRICK
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §4Bronze
    spawn-interval: 1000
    spread: 1.0
  iron:
    item:
    - type: EMERALD
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §2Emerald
    spawn-interval: 10000
    spread: 1.0
  gold:
    item:
    - type: GOLD_INGOT
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §6Gold
    spawn-interval: 20000
    spread: 1.0
  diamond:
    item:
    - type: DIAMOND
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §1Diamond
    spawn-interval: 1000
    spread: 1.0
check-updates: true
update-infos: true
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
specials:
  rescue-platform:
    break-time: 10
    using-wait-time: 20
    item: BLAZE_ROD
    can-break: false
    block: STAINED_GLASS
  protection-wall:
    break-time: 0
    wait-time: 20
    can-break: true
    item: BRICK
    block: SANDSTONE
    width: 5
    height: 3
    distance: 2
  magnetshoe:
    probability: 75
    boots: IRON_BOOTS
  warp-powder:
    show-particles: true
    particle: fireworksSpark
    teleport-time: 6
  trap:
    play-sound: true
    effects:
    - ==: PotionEffect
      effect: 15
      duration: 100
      amplifier: 2
      ambient: true
      has-particles: true
    - ==: PotionEffect
      effect: 18
      duration: 100
      amplifier: 2
      ambient: true
      has-particles: true
    - ==: PotionEffect
      effect: 2
      duration: 100
      amplifier: 2
      ambient: true
      has-particles: true
  tntsheep:
    fuse-time: 8.0
    speed: 0.4
    explosion-factor: 1.0
  arrow-blocker:
    protection-time: 10
    using-wait-time: 5
    item: ender_eye
sign:
  first-line: $title$
  second-line: $regionname$
  third-line: Players &7[&b$currentplayers$&7/&b$maxplayers$&7]
  fourth-line: $status$
player-settings:
  one-stack-on-shift: false
  old-shop-as-default: false
lobbytime-full: 15
hearts-in-halfs: true
spawn-resources-in-chest: true
Console Errors: None
Problem: Players can't PVP. I have tried changing the config but nothing has happened. Both players are in Survival.

**Comment by sebastianbinder** [comment]
You might need to check on your Multiverse Config or your server.properties if pvp is enabled.
