### ISSUE TITLE
Player color (colored leather armor) is erased on game start

### ISSUE THREAD

**Issue by maxosprojects** [BedwarsRel/BedwarsRel#884]
### General Information
- **Version of BedwarsRel**: ``1.3.6 (same on dev branch 606ff8e)``
- **Version of Spigot**: ``1.12``
- **Server Setup**: ``Single server``
- **Installed plugins**: ``Multiverse-Core 2.5.0-b727``
- **Errors on the Console**: no errors

### Problem
Method `Game.start()` cleans all players' inventories and calls `Game.moveFreePlayersToTeam()` which among other things sets leather armor with team's color.
Later method `start()` calls `Game.teleportPlayersToTeamSpawn()` which additionally to teleporting players cleans their inventories.

This issue is raised to be referenced in the upcoming PR to fix this.

**Comment by sebastianbinder** [comment]
The leather armor just indicates the selected team. The cleaning of the players’ inventories including removing their leather armour is an intended behavior because Bedwars traditionally does not have any kit-like start items.
