### ISSUE TITLE
Only one Question:

### ISSUE THREAD

**Issue by LinusHoja** [BedwarsRel/BedwarsRel#888]
Hey guys, jow do you Teleport Players? I alsom am a Minecraft Dev but i have problems with teleporting playersrs with my Plugin because Multiverse blocks it! With your Plugin I don´t have this issue so i want to know how you Teleport players! 

Thank you

Linus Hoja (Germany)

**Comment by sebastianbinder** [comment]
-> https://github.com/BedwarsRel/BedwarsRel
