### ISSUE TITLE
Dumb Rain

### ISSUE THREAD

**Issue by JeffTheL33t** [BedwarsRel/BedwarsRel#900]
It will start raining in my world even though gamerule doWeatherCycle = false and it won't when I do toggle downfall weather clear or even bw reload.
EDIT: This is in 1.12.1 on my Bukkit server.
![fml](https://user-images.githubusercontent.com/30057686/33459436-83f84710-d5ef-11e7-8949-91dc8f95a4b1.PNG)

**Comment by FunnyGameNS** [comment]
Stop the rain BEFORE the game starts.
