### ISSUE TITLE
featherboard and animatednames error

### ISSUE THREAD

**Issue by waiching514** [BedwarsRel/BedwarsRel#902]
![image](https://user-images.githubusercontent.com/29138111/33743276-1719125c-dbe7-11e7-88b9-f090f421b62b.png)

BedwarsRel version: 1.3.6

Problem:
ERROR [FeatherBoard] java.lang.NoClassDefFoundError: io/github/bedwarsrel/BedwarsRel/Main
ERROR [AnimatedNames] Error: Unable to load placeholder from file: bedwarsrel.jar
WARN java.lang.NoClassDefFoundError: io/github/bedwarsrel/BedwarsRel/Main

**Comment by sebastianbinder** [comment]
That’s a FeatherBoard error.
