### ISSUE TITLE
Bedwars shop

### ISSUE THREAD

**Issue by Leonid29-channel** [BedwarsRel/BedwarsRel#907]
How to add more than 9 sentences in bedwars(shop)?
Please tell me.

**Comment by FunnyGameNS** [comment]
Use order option in shop.yml
For example:
10, 20, 30, 40, 50, 60, 70, 80, 90         < Will result in 9 categories
10, 20, 30, 40, 50, 60, 70, 80, 90, 100 < Will result in 10 categories
