### ISSUE TITLE
Some problems about the sign which allows players to join the game.

### ISSUE THREAD

**Issue by endermoon** [BedwarsRel/BedwarsRel#946]
Hello, developers. This is a great plugin, which makes it possible to create own bedwar games. However, unfortunately, I met some problems about the sign which allows players to join the game.
== Description of problem ==
As it mentions in the wiki page 'Step by Step Instructions', a sign with the first line written [bw] and the second line written the game name will allow players to join tht game.
But my game name "war-above-the-sea" needs two lines to finish writing. At this time, if it only allows the game name to be written in the second line, it will not be able to create a sign for this game.
If you put the rest part of the game in the third line, system will not scan the rest part.
![2018-08-16_18.36.26.png](https://i.loli.net/2018/08/16/5b75547a3b1cf.png)
== Version ==
I use BedwarsRel 1.3.6, which runs on Spigot 1.12.

**Comment by Yannici** [comment]
Use an short name like "wats" or "w-a-t-s". I think there is enough space to find a goot game name for one line.
