### ISSUE TITLE
How do i change the Source Code?

### ISSUE THREAD

**Issue by DxsSucuk** [BedwarsRel/BedwarsRel#992]
Hello im Presti and i want to change the Plugin Source Code because i want to set the Server to ingame offline or lobby in the CloudNET API

**Comment by Misat11** [comment]
Click on the Code tab and use green button Clone or download. Also this plugin is discontinued for long time, you can switch to any new bedwars plugin, for example ScreamingBedwars (versions 1.9 - 1.15) if you want.
